### ISSUE TITLE
ایده ای برای کلمات

### ISSUE THREAD

**Issue by aaaamirabbas** [rastikerdar/vazirmatn#100]
سلام . چنتا ایده دارم و نمیدونم که اجرا بشن زیبا تر میشه یا نه برای همین این هارو اینجا در هر پست اعلام میکنم که برسی کنید و اگر صلاح دونستید تغییر بدین .

**ایده اول کلمه لا :**
متوجه شدم کلمه لا در تمام فونت ها چه فارسی و چه غیر فارسی از نوشتار عربی پیروی میکنه و این خب دوست داشتنی نیست داخل نوشتار های فارسی به نظرم .

### برای نمونه تصویر زیر رو ببینید : 

<img src="http://imgurl.ir/uploads/q00252_font.jpg"/>

**این رو روی ساحل و وزیر لطفا پیاده سازی کنید . ممنونم .**

**Comment by rastikerdar** [comment]
سلام
تشکر می‌کنم برای این ایشو.

ایدهٔ نخستی که فرمودین من هر چی فکر کردم متوجه نشدم که چرا از نظر شما مورد اول، فارسی و مورد دوم، عربی به نظر می‌رسه. یعنی نمی‌دونستم همچین چیزی رو. البته راستش من شخصا دستخط پایین شما رو بیشتر می‌پسندم. احتمالا منظور شما شبیه یکان است. و یا شاید نزدیک به حالت زیبای فونت نیکا.
![screenshot from 2018-08-08 09-27-39](https://user-images.githubusercontent.com/3116038/43817216-89705f5c-9aed-11e8-9b87-93344f5fd3b1.png)

![screenshot from 2018-08-08 09-19-44](https://user-images.githubusercontent.com/3116038/43817060-df1c2fa4-9aec-11e8-8c68-62d5c6453787.png)

**Comment by zoghal** [comment]
صابر جان 
اگر لا در حال حاضر بصورت تصویر پیشنهادی خودت نیست من هم موافقم ایده پیشنهادی دوست عزیزمان را مد نظر بگیرید. چون لا فارسی الفش از لام جدا هست.
هرچند در سایز پایین مشخص نمی‌شود و می‌توان هر دو حالت را هم داشته باشیم.

**Comment by ShahriarKh** [comment]
<p dir="rtl">
احیاناً این قضیه مربوط به ligatures نیست؟ تا جایی که می‌دونم می‌شه تنظیم کرد که وقتی حروف ل و ا کنار هم قرار می‌گیرن،  به کدوم شکل نمایش داده بشن. از اونجایی که فونت وزیر فقط برای فارسی نیست و زبان‌های کوردی و عربی و ... رو هم ساپورت می‌کنه، به‌نظرم ایده‌ی خوبی نیست که «عربی‌زدایی» بکنیم!
</p>

**Comment by rastikerdar** [comment]
@ShahriarKh با شما موافقم و بهتره با هر دو زبان هماهنگ بود
با توجه به قدیمی و غیرفعال بودنِ ایشو می‌بندم. ممنونم از مشارکت دوستان.
