### ISSUE TITLE
لود در CDNJS

### ISSUE THREAD

**Issue by mahdiit** [rastikerdar/vazirmatn#105]
لطفا در ول سایت cdnjs
جهت استفاده از سرعت در سایتها بارگزای کنید ممنون میشم

راهنما
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library
#idea #ایده

**Comment by PerseusTheGreat** [comment]
<div dir="rtl">

@mahdiit 
به دلیل تحریم های بین المللی علیه ایران، شبکه تحویل محتوای [cdnjs.com](https://cdnjs.com/) به آدرس های آی پی محدوده ایران، اجازه دسترسی به منابع آزاد را نمیدهد. لذا شما میتوانید از طریق شبکه تحویل محتوای [unpgk](https://unpkg.com/) به آخرین نسخه قلم وزیر (کلیه نسخه ها، ویراست ها و اوزان) دسترسی داشته باشید.
</div>

[https://unpkg.com/vazir-font/dist/](https://unpkg.com/vazir-font/dist/)

**Comment by rastikerdar** [comment]
در حال حاضر یک مورد سی‌دی‌ان داره پشتیبانی میشه. گوگل‌فونتز هم که احتمالا اضافه بشه به نظر میاد دیگه منطقی نباشه بیشتر از این اضافه کنیم. ممنونم برای ایشو و پیشنهادتون.
