### ISSUE TITLE
TTC فرمت

### ISSUE THREAD

**Issue by hamedtorky** [rastikerdar/vazirmatn#108]
سلام برای استفاده در بستر نرم افزاری سطح پایین لازمه فرمت 
ttc 
هم اضافه بشه 

ممنون

**Comment by rastikerdar** [comment]
سلام
راستش من اصلا نمی‌دونم چیه!

**Comment by zoghal** [comment]
یک فرمت قدیمی که چندین وزن یا استایل را در یک فایل نگه می‌دارد:

> What is a TTC file?
> Collection of fonts saved in the TrueType (.TTF) format; used to deliver multiple fonts in a single file; useful for combining fonts that share many glyphs in common.

اما برای من سوال پیش آمد:
> سلام برای استفاده در بستر نرم افزاری سطح پایین لازمه فرمت

این بستر نرم‌افزاری سطح پایین دقیقا چی و چه کاربردی هست؟!
چون این فرمت رسما منسوخ شده مخصوصا با ورود فونت‌های پارامتریک!

**Comment by hamedtorky** [comment]
وقتی روی میکرو کنترلر فونت لود میکنی این فرمت خیلی راخت تر و هماهنگتر با سخت افزار لود میشه

**Comment by rastikerdar** [comment]
متاسفانه امکان پشیتیانی از این فرمت فراهم نیست. با تشکر
