### ISSUE TITLE
اضافه کردن فونت وزیر به فونت های cantarell

### ISSUE THREAD

**Issue by iman-salmani** [rastikerdar/vazirmatn#121]
درود
ضمن تشکر فروان از سازندگان فونت های زیبای وزیر، ساحل، پرستو، صمیم، تنها، گندم، شبنم و وزیرکد
من آگاهی در مورد ساخت فونت ندارم ولی می دانم به این آسانی ها هم نیست فقط یک سوال و درخوست دارم.
همانطوری که می دانید کانترل فونت رسمی گنوم است. راهی هست که فونت وزیر به آن اضافه شده تا دیگر بعد نصب با این تصویر مواجح نشویم.
![gnome-shell](https://8pic.ir/uploads/Screenshot-2019-05-29-Screenshot-from-2019-05-29-15-06-31-png-PNG-Image-1600-×-900-pixels-Scaled-88-.png)

پیش از این یک ایشو برای پشتیبانی زبانی عربی باز شده شاید مفید باشد.
https://gitlab.gnome.org/GNOME/cantarell-fonts/issues/18

**Comment by msm1365** [comment]
دوتا راه برای این قضیه هست

یکی اینکه گنوم فونت وزیر به رسمیت بشناسه و به صورت پیش فرض همراه با انتشار گنوم جدید این فونت هم باشه. و توی تنظیمات وقتی زبان راست چین میشه از این فونت استفاده کنه

راه دومش هم اینه که فونت وزیر روی  سیستم نصب کنید. حالا یا از مخازن رسمی یا به صورت دستی
و با استفاده از برنامه های مختلف که موجود هست فونت های گنوم تغییر بدید

فکر میکنم اگر کاری کنیم که گنوم فونت های جناب راستی کردگار استفاده کنه خیلی بهتره. همه توزیع ها استفاده میکنند. من خودم الان برای اینکه فونت ها وارد مخزن فدورا بشن دارم کار میکنم. تا ببینیم چی میشه

**Comment by rastikerdar** [comment]
سلام
بهتره این موضوع از طریق دوستان بیرون از خود مخزن مثل مواردی که در صفحه مرابخوان آمده انجام بشه. خود مخزن تنها روش ان‌پی‌ام که رایجترین روش است رو ارائه می‌کنه. ممنونم برای این ایشو.
