### ISSUE TITLE
پشتیبانی از زبان‌های فلات ایران

### ISSUE THREAD

**Issue by Javid-Izadfar** [rastikerdar/vazirmatn#13]
متاسفانه قلم از دیگر زبان‌های فلات ایران پشتیبانی نمیکنن. اغلب مشکل عدم چسبیدگی کارکترها را دارنن و بعضا بعضی گلیف‌ها را ندارند.
اگر بتوان از آن‌‌ها نیز پشتیبانی کرد عالی میشه!
ممنونم

**Comment by behdad222** [comment]
@Javid-Izadfar میشه دقیق نام ببرید زبان‌های فلات ایران کدوم‌ها هستند؟
و شماره گلیف‌ها و همینطور شکلشون رو دارید؟
یا منبعی که بشه پیداشون کرد

**Comment by rastikerdar** [comment]
آخ آخ آخ من کلا این ایشو رو فراموش کرده بدوم. خیلی خیلی ببخشید. شرمنده.
ممنونم بهداد.
حقیقتش من خودم اصلا از زبان ها اطلاعی ندارم :(

**Comment by behdad222** [comment]
@rastikerdar من تغریبا لیست تمام گلیف‌هایی که لازمه به همراه شکلشون رو در اوردم
برات میفرستم

**Comment by Javid-Izadfar** [comment]
منظورم از زبان‌های فلات ایرانی، زبان‌هایی مثل کوردی، لوری، آذری، گیلکی، مازنی، پشتو و حتی اردو هست.
متاسفانه به شخصه اطلاعات خاصی در مورد این زبان‌ها و گلیف‌هاشون ندارم و فقط موقع تست قلم متوجه شدم که ساپورت نمیشن.

**Comment by Javid-Izadfar** [comment]
به بزرگواران اهل ویکیپدیای (مخصوصا کوردها و لورها)، درخواست کمک دادم. انشالا که به اینجا سر خواهند زد :)

**Comment by rastikerdar** [comment]
ممنونم بابت پیگیریتون.
راستی در مورد مسائل دیگر مربوط به فونت از جمله ظاهرش یا ایراداتش و وبسایتش و انتقاد و شیوه توسعه و ... هم نظری داشتید بفرمایید. کلا هر چیزی در مورد فونت به ذهنتون میرسه بگید چون نظرات  در مورد فونت وزیر خیلی کمه و توسعه در فضای مبهمی انجام میشه.

سپاس

**Comment by Javid-Izadfar** [comment]
در حال حاضر، در حال استفاده کردن از این قلم روی چند پروژه  هستم و تا الان به مشکلی بر نخوردم و از ظاهر قلم نسبتا راضی بودم (خودم ترجیح میدم ـه متصل باشه به بدنه ). اما اگه در آینده مسئله ای پیش اومد حتما مزاحمتون میشم!!
پیروز باشید

**Comment by rastikerdar** [comment]
نسخه جدید را ببینید. خیلی تغییر کرده به نسبت سری یک. کلا عوض شده.
[rastikerdar.github.io/vazir-font](http://rastikerdar.github.io/vazir-font/)

**Comment by aso-mehmudi** [comment]
سلام. خسته نباشید. ئاسۆ هستم از ویکیپدیای کردی
برای زبان کردی علاوه بر حروف فارسی و عربی و انگلیسی این حروف لازمن:
الفبای استاندارد لاتین کردی : ÊÎÛÇŞẌḦ êîûçşẍḧ
الفبای استاندارد عربی کردی:  ڵ ۆ ێ ڕ ە ھ ڤ  
توجە: «ه» و «ە» و «ھ» متفاوتن
البتە برای بعضی گویشهای دیگهٔ کردی اینها هم استفادە می شن: ڎ ۊ ۮ
تا اونجایی که من خبر دارم لری الفبای استاندارد نداره و اونی که الان تو ویکی لری هست همه‌گیر نیست و فقط چند نفر فعالی که ویکی لری رو راه انداختن ازش استفاده می‌کنن.
توجه: رفتار این یونیکدها باید دقیقا شبیه آخرین ورژن فونت‌های معروف مثل امیری و دژاوو باشه
با سپاس فراوان

**Comment by rastikerdar** [comment]
خیلی از شما ممنونم.
 آقا بهداد این که خیلی خوب میشه البته اگر می تونستید رو گیت هابتون بزارید که خیلی بهتر میشد.

@aso-mehmudi 
آقای محمودی واقعا لطف کردید. سپاس فراوان.

**Comment by Javid-Izadfar** [comment]
بعد از صحبت با یکی از دوستان لر زبان (جناب ساکی)، ایشون یک سری منابع لوری در اختیارم قرار دادند که فک میکنم بد نباشه شما هم داشته باشید.
صفحه کلید لوری: https://incubator.wikimedia.org/wiki/Wp/lrc/%D8%B5%D9%81%D8%AD%D9%87_%DA%A9%D9%84%DB%8C%D8%AF_%D9%84%D9%88%D8%B1%DB%8C
duleri.rar: https://drive.google.com/file/d/0B8Z6v0QCJQjQMjl5bDkzbHV6NUU/view
 رسم الخط لری دومنی: https://drive.google.com/file/d/0B8Z6v0QCJQjQSURWY3g0MFRCWEE/view
Per_Eshkeft.tff: https://drive.google.com/file/d/0B8Z6v0QCJQjQU1o3X1pDUzEwU00/view

**Comment by zoghal** [comment]
@Javid-Izadfar :+1:

**Comment by Javid-Izadfar** [comment]
@zoghal جناب سوزنچی شما هم که اهل فن هستید، چه راه حلی برای ساپورت این زبون‌ها دارید؟

**Comment by behdad222** [comment]
@Javid-Izadfar مگه پیچیده هست؟
اگر بخوای کامل ساپورت کنی کل بلاک عربی یونیکد و پرزنتیشن فورم‌ها رو میشه پیاده کرد

**Comment by zoghal** [comment]
@Javid-Izadfar  در ساپورتش که مشکلی نیست. همین که بهداد میگه کفایت میکنه. مشکل در عاقبتش هست.
@behdad222  پیچیده نه. اما کفر طراح رو در میاره. حساب کنید اگر بخواد کل بلوک‌های arabic رو ساپورت کنه و کرنینگ مناسب هم داشته باشد. چقدر زمان خواهد برد. و چه حجمی به فونت مخصوصا فونت وب اضافه میکند. حساب کردید حاصل رو در وزن ها ضرب کنید. آنگاه متوجه اصل داستان خواهید شد. :دی

**Comment by behdad222** [comment]
@zoghal همه گلیف‌ها که طراحی نمیشند که بخوایم براشون کرنینگ جدا داشته باشیم و حجم به فونت اضافه کنند
pfont حدود ۴۰۰ گلیف داره
و سعی کردیم گلیف زبان‌هایی رو اضافه کنیم که از این حرف استفاده می‌کنند
لیستش رو به زودی منتشر می‌کنیم تا بقیه هم استفاده کنند

**Comment by zoghal** [comment]
@behdad222 خوشتیپ چه ربطی به طراحی دارد!!. اینکه تو یک گلیف چه شیپی استفاده بشه و آنهم به چه صورتی (رفرنس/کامپوننت) ارتباطی با تعریف کرنینگ و تنظیمات اوپن تایپ ندارد. برای هر گلیف که تعریف میشه. کرنینگ جدا تعریف میشه. البته میشه یک گروه تعریف کرد برای تعدادی از حروف با خصوصیت یکسان ، اما در بعضی از حروف مثل و با ؤ در کنار کاف ممکنه نیاز به کرنینگ جدا نیاز باشد.

**Comment by behdad222** [comment]
درسته
من کرنینگ رو با اسپیسینگ اشتباه گرفتم
@zoghal

**Comment by aziz** [comment]
به نظر قلم آزاد فارسی که به تازگی منتشر شده لیست خیلی خوب و کاملتری از گلیف‌های زبان‌های فلات ایران داره. 
به نظرم صابر جان بهتره تو هم خودت رو به همون لیست برسونی  تا یه جورایی یه لیست توافق شده‌ای بوجود بیاد. 

@behdad222 تبریک میگم به تو و طراح خوب این قلم و همه بچه‌هایی که کمک کردند.

**Comment by rastikerdar** [comment]
وای چقدر زیــــــــــاده!
:)

**Comment by rastikerdar** [comment]
بنا به درخواست کاربران در طول زمان توسعه چند زبان دیگر به فونت اضافه شد. ممنونم از مشارکت دوستان
https://rastikerdar.github.io/vazirmatn/fa/lab
