### ISSUE TITLE
کمبودهای فونتهای وزیر و ساحل

### ISSUE THREAD

**Issue by farshadrasuli** [rastikerdar/vazirmatn#143]
بابت تهیه این فونتهای زیبا از شما سپاس‌گزارم. برای کاملتر شدن این فونتها، چند نویسه که جا مانده را به شما یادآوری میکنم. امیدوارم در نسخه‌های بعدی این فونتها لحاظ شوند.

**نویسه‌های ضروری** (مورد نیاز در [استاندارد ۹۱۴۷](http://standard.isiri.gov.ir/StandardView.aspx?Id=609) یا نوشتارهای علمی مانند مورد شمارهٔ چهار)
1. نویسهٔ تقسیم [Division Sign](https://unicode-table.com/en/00F7) ÷
2. نویسهٔ ضربدر [Multiplication Sign](https://unicode-table.com/en/00D7) ×
3. نویسهٔ خط تیره [Hyphen](https://unicode-table.com/en/2010)
4. نویسهٔ خط تیره نشکن [Non-Breaking Hyphen](https://unicode-table.com/en/2011)
5. نویسهٔ [Figure Dash](https://unicode-table.com/en/2012)
6. نویسهٔ نشانهٔ چپ به راست [Left-To-Right Mark](https://unicode-table.com/en/200E)
7. نویسهٔ راست به چپ [Right-To-Left Mark](https://unicode-table.com/en/200F)
8. نویسهٔ زیر متن چپ به راست [Left-To-Right Embedding](https://unicode-table.com/en/202A)
9. نویسهٔ زیر متن راست به چپ [Right-To-Left Embedding](https://unicode-table.com/en/202B)
10. نویسهٔ پایان زیر متن [Pop directional Formatting](https://unicode-table.com/en/202C)
11. نویسهٔ زیر متن اکیداً چپ به راست [Left-To-Right Override](https://unicode-table.com/en/202D)
12. نویسهٔ زیر متن اکیداً راست به چپ [Right-To-Left Override](https://unicode-table.com/en/202E)
13. نویسهٔ [Arabic Letter Alef Wasla](https://unicode-table.com/en/0671)
14. نویسهٔ یای مقصوره [Arabic Subscript Alef](https://unicode-table.com/en/0656)

**نویسه‌های دسته دوم** (وجود این نویسه‌ها سبب کامل شدن فونت میشود)
1. نویسهٔ پایان اثبات [End of Proof](https://unicode-table.com/en/220E)
2. نویسهٔ مربع تو پر [Black Square](https://unicode-table.com/en/25A0)
3. نویسهٔ نشان ص [Arabic Sign Sallallah Alayhe Wassallam](https://unicode-table.com/en/0610)
4. نویسهٔ نشان ع [Arabic Sign Alayhe Assallam](https://unicode-table.com/en/0611/)
5. نویسهٔ نشان رح [Arabic Sign Rahmatullah Alayhe](https://unicode-table.com/en/0612/)
6. نویسهٔ نشان س [Arabic Small High Seen](https://unicode-table.com/en/06DC/)
7. نویسهٔ پایان آیه [Arabic End of Ayah](https://unicode-table.com/en/06DD/)
8. نویسهٔ شروع حزب [Arabic Start of Rub El Hizb](https://unicode-table.com/en/06DE/)
9. نویسهٔ سجده [Arabic Place of Sajdah](https://unicode-table.com/en/06E9/)

**Comment by rastikerdar** [comment]
متشکرم برای این ایشو

**Comment by rastikerdar** [comment]
توی نسخه جدید وزیر یعنی ۲۵.۰.۰ تمام گلیف‌های دسته نخست اضافه شد. دسته دوم برای نسخه‌های آینده ماند.

**Comment by rastikerdar** [comment]
در نسخه جدید وزیر یعنی ۲۶ بخش دوم نویسه‌ها نیز (به جزء نویسهٔ مربع تو پر) اضافه شد.
فونت ساحل در نسخه‌های آتی
