### ISSUE TITLE
فونت کوچک وزیر

### ISSUE THREAD

**Issue by kookma** [rastikerdar/vazirmatn#159]
اگر اشتباه نکنم فونت فعلی وزیر بیشتر استفاده در محتوای وب و آنلاین و اپلیکشن را هدف  دارد.
زیبایی این فونت میتواند در تایپ کتاب و گزارش و پایان نامه بکار آید.

آیا این امکان هست که نسخه کوچک فونت مانند پرستو پرینت ارایه شود که بتوان جایگزین فونت‌های پر کاربر میترا زر و نازنین کرد.
این فونت ها در محیط دانشگاه بسیار مورد استفاده است اما نسخه رایگان موجود اشکالات متعدد دارد

زیبایی و خوانایی فونت وزیر میتواند آن را گزینه بسیار خوبی برای استفاده در متون چاپی نماید.

با سپاس

**Comment by rastikerdar** [comment]
ممنونم برای این ایشو. درست می‌فرمایید. نسبت استفاده از وزیر در فضای دیجیتال بیشتره. امکان ارائه نسخه کوچک چاپی هم وجود داره اما کمی اوضاع رو پیچیده می‌کنه. چون بر خلاف فونت لاتین در فونت فارسی با انواع نسخه‌ها مواجه شده‌ایم.

البته در مورد اشکالات متعدد فونت‌هایی که فرمودین، اگر اشتباه نکنم فونت‌های اصلاح شده توسط شورای عالی اصلاع رسانی گزینه بهتری نسبت به دیگر نسخه‌های رایگان باشند.

**Comment by vaheedxp** [comment]
من فکر نمی‌کنم فونت وزیر برای کتاب مناسب باشد. البته در مواد چاپی غیر رسمی مثل جزوه می‌تواند بر خوانایی بیفزاید. در مورد فونت‌های معمول چاپی، فونت‌های مریم‌سافت بسیار عالی و اصلاح‌شده هستند. میترا، نازنین، لوتوس و زر در نرم‌افزار قلم برتر این شرکت هست.

**Comment by kookma** [comment]
> من فکر نمی‌کنم فونت وزیر برای کتاب مناسب باشد. البته در مواد چاپی غیر رسمی مثل جزوه می‌تواند بر خوانایی بیفزاید. در مورد فونت‌های معمول چاپی، فونت‌های مریم‌سافت بسیار عالی و اصلاح‌شده هستند. میترا، نازنین، لوتوس و زر در نرم‌افزار قلم برتر این شرکت هست.

فونت پرستو پرینت بسیارخروجی خوبی می دهد و از نازنین به نظر مناسب تر است.
اما تنوع وزن وزیر را ندارد از این جهت من خواهش کردم وزیر برای نشر رو میزی در صورت امکان منتشر شود.

**Comment by rastikerdar** [comment]
البته به نظر میاد پرستو ازش استقبال نشد. یعنی من استفاده‌ای ندیدم جز چند مورد.

**Comment by vaheedxp** [comment]
![Screenshot_20200722-204652_Samsung Internet](https://user-images.githubusercontent.com/34465387/88201132-58f91d80-cc5c-11ea-9f56-f2bf12574caf.jpg)
جناب راستی‌کردار ما در زبان اوزبیکی افغانستان دو حرف خاص داریم که در فونت وزیر نیست. اگه این دو حرف اضافه بشه ممنون خواهیم شد. این دو حرف فکر کنم در زبان‌های دیگری هم کاربرد داره به نظرم. در تصویر ببینید. یا از لینک زیر چک کنید.
gahwara.com/uz

**Comment by rastikerdar** [comment]
@vaheedxp اگر براتون مقدوره این کامنت رو به صورت یک ایشوی جدید ثبت بفرمایید.
آن دو حرف مد نظرتون رو هم تایپ کنید.

**Comment by kookma** [comment]
> البته به نظر میاد پرستو ازش استقبال نشد. یعنی من استفاده‌ای ندیدم جز چند مورد.

در دانشگاه امیرکبیر من میبینم بچه‌ها برای پروژه‌های پایانی از پرستو پرینت استفاده می کنند. خروجی خیلی خوبی می دهد به ویژه پشتیبانی از حروف انگلیسی نمایش درست تعداد با ممیز و موقعیت مناسب ممیز
