### ISSUE TITLE
عدم ثابت ماندن اعداد فارسی در طول یک رشته، حین تغییر

### ISSUE THREAD

**Issue by RezaSh13** [rastikerdar/vazirmatn#165]
[f.zip](https://github.com/rastikerdar/vazir-font/files/5107527/f.zip)

تو فایل ویدیویی بالا کاملا این مشکل رو نشون میده که حین تغییر رشته طول رشته تغییر میکنه

**Comment by rastikerdar** [comment]
بلی همینطوره. البته این موضوع در ایشو‌های #78 و #98 نیز مطرح شده است.

**Comment by aminabedi68** [comment]
برای این مورد میشه از
```tnum```
استفاده کرد که یه جایگزینی تکی بین عدد اصلی و عدد متناظر با عرض ثابت انجام میده. البته کارکرد درستش بستگی به تنظیم خود سیستم عامل داره(که این تگ رو اونجا فعال کرده باشه) چون تو این وضعیت مستقیما به خود کدپوینت اشاره نمیشه(برای عربی وجود نداره احتمالا). با این حال به احتمال زیاد با این روش کار میکنه

**Comment by rastikerdar** [comment]
اگر مشکلتون با استفاده از روشی که از نسخه ۳۰ به بعد در فونت قرار داده شده رفع میشه پس دیگه می‌تونیم این ایشو رو ببندیم. در ایشوی زیر بیان شده:
#198
