### ISSUE TITLE
کاربرد نسخه UI

### ISSUE THREAD

**Issue by sajaddp** [rastikerdar/vazirmatn#174]
<div dir="rtl">
سلام <br>
وقت بخیر.<br>
چه قدر خوب می شود که اگر کاربرد هر نسخه را هم در فایل readme بنویسید. برای مثال نسخه UI که در ورژن ۲۷ قرار گرفته برای استفاده در وب و اپلیکیشن ها هست یا برای کاربری گرافیکی مناسب هست؟<br>

</div>

**Comment by rastikerdar** [comment]
سلام و سپاس.
این حالت فکر نمی‌کنم توی کارهای گرافیکی کاربردی داشته باشه. بیشتر برای همان رابط کاربری مفیده. درخواست‌های متعددی برای این حالت شده بود که همه‌اش به رابط کاربری مربوط بود. در مورد توضیحات حق با شماست. انواع نسخه‌ها و فایل‌ها نیاز به توضیح داره.

**Comment by rastikerdar** [comment]
با توجه به اضافه شدن توضیحات این نسخه در صفحه راهنما فکر می‌کنم تا حدودی کفایت کنه. ممنونم برای پیشنهادتون.
https://rastikerdar.github.io/vazirmatn/fa/docs/HELP-fa
