### ISSUE TITLE
مشکل نسخه ui

### ISSUE THREAD

**Issue by habibnajafi** [rastikerdar/vazirmatn#184]
سلام 
ممنون به خاطر اضافه کردن نسخه ui 
اما هنوز هم کمی از متن در سیستم عامل هایی مثل اندروید قابل مشاهده نیست ولی خیلی کم شده و بهتر شده
![IMG_20201231_133528](https://user-images.githubusercontent.com/714767/103405668-145ba180-4b6d-11eb-8c61-f3bfba932abf.jpg)
مثل این مورد که استفاده از فونت وزیر در واتساپه که کمی از متن کلمه دیروز قابل مشاهده نیست اما با نسخه قبلی خیلی تفاپت داره و‌بهتر شده 
مورد دوم آیا این امکان وجود داره که نسخه بولد و‌معمولی هر دو در یک فایل تی تی اف باشند؟

**Comment by habibnajafi** [comment]
کلمه دیروز هم هنوز خیلی پایینتر از اعداد افتاده

**Comment by AliDjango** [comment]
چطوری فونت رو به واتساپ اضافه کردید؟@habibnajafi

**Comment by AbbasAlimi** [comment]
> سلام ممنون به خاطر اضافه کردن نسخه ui اما هنوز هم کمی از متن در سیستم عامل هایی مثل اندروید قابل مشاهده نیست ولی خیلی کم شده و بهتر شده ![IMG_20201231_133528](https://user-images.githubusercontent.com/714767/103405668-145ba180-4b6d-11eb-8c61-f3bfba932abf.jpg) مثل این مورد که استفاده از فونت وزیر در واتساپه که کمی از متن کلمه دیروز قابل مشاهده نیست اما با نسخه قبلی خیلی تفاپت داره و‌بهتر شده مورد دوم آیا این امکان وجود داره که نسخه بولد و‌معمولی هر دو در یک فایل تی تی اف باشند؟

سلام
این فونت‌ها را امتحان کنید.
https://bayanbox.ir/download/7346626180324388433/Fonts.7z
