### ISSUE TITLE
تفکیک‌کردن فایل‌ها بر اساس فرمت

### ISSUE THREAD

**Issue by xmha97** [rastikerdar/vazirmatn#190]
سلام
الان دیدم که فونت
[CascadiaCode](https://github.com/microsoft/cascadia-code/releases)
ماکروسافت به این صورت منتشر شده است
این کار باعث می‌شود که نصب‌کردن فونت‌ها را آسان‌تر شود
![File Explorer](https://user-images.githubusercontent.com/23485114/107874491-4895e200-6ecf-11eb-9b3c-0eeb637a8b86.png)
با تشکر

**Comment by rastikerdar** [comment]
سلام
درست می‌فرمایید. وضعیت فایل‌ها شلوغ و درهم به نظر میرسه. از بس که فونت فارسی نسخه‌های مختلف داره ساختار الکی طولانی شده. باید تغییراتی در اسکریپت تولید فایل‌های خروجی انجام بشه.

**Comment by xmha97** [comment]
ممنون از شما 🙏

**Comment by rastikerdar** [comment]
این کار در وزیرمتن ۳۲ انجام شد و ساختار نامگذاری و پوشه‌بندی تغییر کرد:
https://github.com/rastikerdar/vazirmatn/releases
ممنون
