### ISSUE TITLE
مشکل در نمایش حرف "ي" در نسخه UI

### ISSUE THREAD

**Issue by sepehr-brj** [rastikerdar/vazirmatn#194]
در نسخه UI
نقطه‌های حرف عربی ي نمایش داده نمیشوند

**Comment by rastikerdar** [comment]
این نسخه یو‌آی برای زبان فارسی مناسبه چون ارتفاعش کم شده و به همین دلیل هرچی که بالا و پایین این ارتفاع قرار گرفته باشه حذف میشه. از جمله برخی اعراب و ...
اما برای چند زبانه‌ها از همان نسخه اصلی یا استاندارد که در ریشه بسته قرار داره باید استفاده بشه. در محیطی که هم زبان فارسی به عنوان زبان ثانوی محسوب می‌شه (و نه اولیه) هم بهتره از نسخه اصلی استفاده بشه. نسخه یوآی یه جور هک برای کسانی بود که به ارتفاع قلم اعتراض داشتند.

**Comment by rastikerdar** [comment]
در وزیرمتن ۳۲ این مشکل رفع شد. اگر پیشنهاد من غالبا استفاده از نسخه استاندارد است.
https://github.com/rastikerdar/vazirmatn/releases
ممنون
