### ISSUE TITLE
یکسان‌نبودنِ نامِ خانوادهٔ فونت

### ISSUE THREAD

**Issue by kokabi1365** [rastikerdar/vazirmatn#203]
<div dir="rtl">
در فریم‌ورکِ WPF، نامِ خانوادهٔ فونت (Family name) بعد از علامتِ # می‌آد:

[`<FontFamily x:Key="VazirUi">pack://application:,,,/Resources/Fonts/#Vazir FD-UI</FontFamily>`](https://github.com/kokabi1365/Vajehdan/blob/e5820689f695cc547ae9e85db407c8c7628ea5d0/src/Vajehdan/App.xaml#L16) 

حالا اگر اسمِ خانوادهٔ فونت یکسان نباشه هیچ یک از فونت‌هایِ اون خانواده تشخیص داده نمی‌شه که از قضا فونتِ شما هم مثلِ ایران‌سنس این مشکل رو داره. این در حالیه که در فونتی مثلِ Concolas خانوادهٔ همهٔ فونت‌ها یکسان هست و به‌راحتی می‌شه در WPF استفاده کرد.

<div dir="ltr">

![Screenshot 2021-05-28 163119](https://user-images.githubusercontent.com/44271870/120614319-56667780-c46c-11eb-8f95-e6a30e9c8276.png)

من با فونت‌فورج، به صورتِ دستی، خانوادهٔ تمامِ فونت‌هایِ وزیر رو یکسان‌سازی کردم و کارم راه افتاد. می‌خواستم تغییرات رو در سورسِ پروژه هم اعمال کنم؛ ولی تویِ ویندوز هر کاری کردم نتونستم اسکریپت build.py رو اجرا کنم. با کالی لینوکس هم در vmware کلی مشکل پیدا کردم. خلاصه دردسرش زیاد بود گفتم خودتون زحمتش رو بکشید. 
</div>
</div>

**Comment by rastikerdar** [comment]
ممنونم برای این ایشو. مشکل اینجاست که برای نمایش صحیح خانواده فونت‌ها در برنامه‌ها مجبور به انجام این روش شدم. خود فونت روبوتو هم از این روش استفاده کرده:
![Screenshot at 2021-06-03 15-37-37](https://user-images.githubusercontent.com/3116038/120635367-a4d24100-c481-11eb-9bc9-d6123a427d5f.png)

الان در ویندوز درست کار میکنه:
![Screenshot at 2021-06-03 15-31-17](https://user-images.githubusercontent.com/3116038/120634679-c54dcb80-c480-11eb-9875-1146eab4557f.png)

توی این قسمت خانواده فونت درست تعریف شده:
![Screenshot at 2021-06-03 15-39-18](https://user-images.githubusercontent.com/3116038/120635598-e5ca5580-c481-11eb-9219-9a251b611f37.png)

اگر تغییر بدم ممکنه برای فریمورک مد نظر شما درست بشه اما برای بقیه دچار مشکل میشه. ولی باید بیشتر بررسی کنم (هم لینوکس و هم ویندوز)

برای اجرای اسکریپت‌های پروژه هم باید یک داکر ایمیجی درست کنم که هر کس خواست بدون دردسر اجرا کنه، چون تمام وابستگی‌ها باید نصب باشه و هر جا که به مشکل بر بخوره کنسل یا ناقص میشه..

**Comment by kokabi1365** [comment]
<div dir="rtl">
فکر کنم یه چیزایی فهمیدم 🙂 

ویندوز فقط سه استایلِ Regular, Bold, Bold Italic رو می‌شناسه و ظاهراً فقط برای این استایل‌ها می‌شه Family name یکسانی انتخاب کرد و برایِ بقیهٔ استایل‌ها باید نامِ استایل رو به نامِ پایه در Family name اضافه کرد. مثلاً همین فونتِ روبوتو برایِ استایل‌هایِ Regular, Bold, Bold Italic، خانوادهٔ فونت رو Roboto گذاشته و برای بقیهٔ فونت‌ها، زوج به زوج نامِ استایل رو به خانوادهٔ فونت اضافه کرده؛ مثلاً برای Medium و Medium Italic خانوادهٔ فونت رو Roboto Medium گذاشته و Black و Black Italic رو Roboto Black گذاشته. فونتِ شما برای Bold و Regular خانواده رو Vazir UI نشون می‌ده؛ ولی برای Black به جای Vazir UI Black نامِ خانواده رو Vazir Black UI نشون می‌ده که خلافِ انتظاره. البته اگه FontForge خودش به صورتِ خودکار نام‌گذاری می‌کنه داستان پیچیده‌تر می‌شه. 

---

این چندتا لینک هم بخونید. 
خودم فرصت نکردم.

https://github.com/google/fonts/issues/2394
https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids
https://www.fonttutorials.com/how-to-name-font-family/

مشکل رو حل کردید حتماً یه مقاله‌ای در ویرگول منتشر کنید.
خیلی مشتاقم بدونم داستانش چیه.


</div>

**Comment by rastikerdar** [comment]
احتمالا داستانش همینه. من از اول اشتباه کردم که نامگذاری رو برای نسخه‌های جانبی درست انجام ندادم. چون تا الان مشکلی ایجاد نشده بود رها شده بود اما الان با گزارش شما معلوم شد که بالاخره از یک جایی خودش رو نشون میده. باید اسکریپت‌ها رو برای نسخه بعدی اصلاح کنم.
ممنونم برای گزارش این ایراد.

**Comment by rastikerdar** [comment]
شیوه نامگذاری کلا تغییر کرد. امیدوارم این مشکل به شکل استاندارد رفع شده باشه:
https://github.com/rastikerdar/vazirmatn/releases
باز هم مشکلی بود ممنون میشم گزارش بدین.

**Comment by kokabi1365** [comment]
خسته نباشید.
نسخهٔ جدید فونت رو همین الان چک کردم، همه‌چی درست بود.
