### ISSUE TITLE
نام فونت‌های عادی و بولد فونت یکسان هستند

### ISSUE THREAD

**Issue by sepehr-brj** [rastikerdar/vazirmatn#204]
![Vazir](https://user-images.githubusercontent.com/55192376/121517276-69e18780-ca04-11eb-957f-e88696277cc4.PNG)

این مشکل در تمام نسخه‌ها (یو‌آی و بدون حروف لاتین و ...) وجود دارد

**Comment by rastikerdar** [comment]
در مورد فونت‌های فارسی غیر از خانواده وزیر چی؟ یا فونت‌های لاتین. اونها رو هم غیر از این حالت نشون میده؟

**Comment by sepehr-brj** [comment]
بله فونت‌های ساحل و
Segoe UI
هم این مشکل رو دارن
توی پوشه فونت‌های نصب شده هم نسخه معمولی و هم نسخه بولد این فونت‌ها هستن ولی بخاطر اینکه اسمشون یکیه نمیتونم توی ورد همزمان از بولد و عادی استفاده کنم (فقط عادی توی لیست فونت‌ها هستش) و هر بار باید عادی رو پاک کنم تا بتونم از بولد استفاده کنم

**Comment by rastikerdar** [comment]
نیازی به پاک کردن فونتی نیست. معمولا حالت ضخیم هیچ فونتی در لیست نمی‌آید. برای  **بولد** کردن در وُرد از دکمه بولد کردن استفاده کنید یا از ترکیب کلیدهای:
CTRL+B
