### ISSUE TITLE
میزبانی ریلیز در یک برنچ

### ISSUE THREAD

**Issue by parsedarweb** [rastikerdar/vazirmatn#21]
سلام

اگر امکانش هست یک برنچ ایجاد کنید که آخرین ریلیز توی اون باشه. اینطوری ما می تونی اون رپو رو در پروژه هامون روی گیتهاب معرفی کنیم تا لازم نباشه با هر ریلیز، دستی فایلهای فونت جدید رو جایگزین کنیم.
‫ اگر فرض کنیم این رپو اسمش last باشه،ما می تونیم رپوی last رو در پوشه فونت پروژه گیتهابی خودمون تعریف کنیم.

مرسی از زحمتی که بابت توسعه می کشید

**Comment by Javid-Izadfar** [comment]
<p dir='rtl'>سلام</p>

<p dir='rtl'>شما می‌تونید با گذاشتن `/latest` به انتهای پیوند ریلیز‌ها، آخرین ریلیز رو داشته باشید. یعنی:</p>
[https://github.com/rastikerdar/vazir-font/releases/latest](https://github.com/rastikerdar/vazir-font/releases/latest)

**Comment by parsedarweb** [comment]
‫منظور من ناین نبود!
اونجا که شما لینک دادی، فایلهای فشرده است. منظور من یک رپو است که که فایلهای فونتها رو داشته باشه، یعنی همون محتوای داخل فایلهای فشرده که ریلیز میشه، در یک رپو/برنچ قرار بگیره که بتونیم اون رو در رپوی پروژه خودمون لینک کنیم

**Comment by rastikerdar** [comment]
سلام
تشکر می کنم برای این ایشو
فکر می کنم این ایشو به #17 و #11 مرتبط باشه.
به نظر میاد باید فکری براش بشه. حالا یک ریپو جدا یا یک برنچ جدا.

**Comment by zoghal** [comment]
@parsedarweb ایا شما میخواهید مخزن فونت رو به صورت ساب مازول استفاده کنید؟

**Comment by parsedarweb** [comment]
> ایا شما میخواهید مخزن فونت رو به صورت ساب مازول استفاده کنید؟

[بله، دقیقا](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by parsedarweb** [comment]
چی شد، برنامه‌ای برای رپوی نسخه رندرشده دارید؟

**Comment by rastikerdar** [comment]
در حال حاضر توی ریپوی اصلی نسخه رندر شده قرار دارد.
پوشه dist

با باور هم می تونید نصب کنید:
bower install vazir-font --save

**Comment by parsedarweb** [comment]
> در حال حاضر توی ریپوی اصلی نسخه رندر شده قرار دارد.
> پوشه dist

اونجا باشه فایده نداره  چون  نمی شه یک بخش از یک رپو رو ساب-ماژول کرد.  ساب-ماژول روی رپو کار می کنه

> bower install vazir-font --save

‫چی هست؟! روی سیستم نصب می کنه؟! مشکلی برای نصب روی سیستم ندارم. می خوام آخرین نسخه فونت رو توی پروژه هام  اتوماتیک داشته باشم. تعداد پروژه هام زیاده و نسخه های فونت تندتند بالا می ره و سخته که مدام دستی به آخرین نسخه بروز کنم

لطفا یک رپو/برنچ برای فونتهای رندر شده تعبیه کنید
به جای اون پوشه دیست چرا در یک برنچ نمیریزید؟

**Comment by zoghal** [comment]
فکر کنم برای این فونت های فارسی باید یک پلاگین برای این ابزار ها  بنویسیم. یک چیزی تو مایه های پلاگین glup

**Comment by geminorum** [comment]
- ساب ماژول رویکرد مناسبی برای مدیریت دیپندنسی‌ها نیست.
- احتیاجی هم به گالپ یا گرانت، برای کاری غیر از توسعه نیست.
- فعلن راهکار اصلی و استاندارد برای استفاده در فرانت‌اند، همون بوور هست. اگر آشنایی ندارین: (bower.io)[http://bower.io/]
- فکر نمیکنم احتیاجی هم حتی به پکیچ ان‌پی‌ام باشه، چون آیکون فانت نیست. (بر خلاف فانت آوسوم)

**Comment by parsedarweb** [comment]
‫bower برای وقتی مناسبه که بخوام خودم آپدیت توزیع شده انجام بدم!
‫اما با ساب‌ماژول مشتری رو رها می‌کنم و همه چیز خودش پیگیری می‌شه.

**Comment by rastikerdar** [comment]
متاسفانه امکان انجام این کار وجود نداره به ویژه اینکه ساختار پروژه تقریبا تثبیت شده. ممنون
