### ISSUE TITLE
مشکل در کرنینگ حروف انگلیسی وزیر UI

### ISSUE THREAD

**Issue by hamid0740** [rastikerdar/vazirmatn#218]
<div align=right>

آقای راستی‌کردار سلام
اگر به حرف "تی" در کلمات توجه کنید، متوجه خواهید شد در هنگام اتصال به برخی حروف دیگر دچار فرو رفتگی بیش از حد می‌شوند و تشخیص کلمه ناممکن می‌شود. ممکن است این اشکال در برخی حروف دیگر هم باشد، اما به آنها دقت نکرده باشم.
لطف کنید و این اشکال را هم رفع کنید.

</div>

**Comment by rastikerdar** [comment]
سلام
ممنونم برای این ایشو. اگه ممکنه تصویری از این مشکل اینجا بگذارید و اینکه بفرمایید در چه برنامه‌ای به این مشکل برخوردید.

**Comment by rastikerdar** [comment]
در نسخه وزیرمتن ۳۲ تقریبا تمام مشکلات لاتین به دلیل تغییر شیوه ترکیب آن برطرف شد:
https://github.com/rastikerdar/vazirmatn/releases
ممنونم برای گزارش این ایراد
