### ISSUE TITLE
Not appearing well on Safari

### ISSUE THREAD

**Issue by roj1512** [rastikerdar/vazirmatn#220]
What are these spaces between the letters in the `<h1>` tag? URL: https://bw.rojser.best/
![image](https://user-images.githubusercontent.com/49933115/140329849-147092d1-ce87-4d95-a73a-c9e09b2069af.png)

**Comment by rastikerdar** [comment]
سلام
تشکر می‌کنم برای این ایشو. اگر درست متوجه شده باشم از تصویر اینطور به نظر میاد که برای اون قسمت از متن فاصلهٔ بین حروف توسط خود طراح یا برنامه‌نویس افزایش یافته که این موضوع ارتباطی به خود فونت نداره.

**Comment by rastikerdar** [comment]
It looks like that the programmer or designer has increased `letter-spacing` property for that part of text.

**Comment by X7md** [comment]
> It looks like that the programmer or designer has increased `letter-spacing` property for that part of text.

Something safari has an issue with unavailable font-weight.

for example if I don't include font-800 and use it,
 ```css 
font-weight: 800;
 ```
 Safari will show some letters spacing.

**Comment by roj1512** [comment]
@X7md I think it's because I'm importing a single `.ttf` file, can you make sure? If it's right, I'll close this.

**Comment by rastikerdar** [comment]
Do you still have this issue with the latest version? You can test on this page:
https://rastikerdar.github.io/vazirmatn/en/lab

**Comment by roj1512** [comment]
My bad, I f*cking forgot to close it 2 months ago.
