### ISSUE TITLE
مشکل متن فقط در گوشی در حالت جاستیفای(justify)

### ISSUE THREAD

**Issue by mehdiahadi** [rastikerdar/vazirmatn#221]
![vazir](https://user-images.githubusercontent.com/93978239/140900042-8c145585-cd9f-4e4d-89a7-20b8d293a61f.jpg)

**Comment by rastikerdar** [comment]
ممنونم برای این ایشو.
به نظر میاد این نسخهٔ وزیر توی تصویر، قدیمیه. در نسخه‌های اخیر خوشبختانه این مشکل رفع شده.
