### ISSUE TITLE
درخواست وزن های ضخیم تر

### ISSUE THREAD

**Issue by RyanNorooz** [rastikerdar/vazirmatn#224]
### تبریک بابت توسعه بهترین فونت open-source فارسی 🥳

این فونت همین الان هم عالیه ولی اگه میشد وزن های ضخیم تری ازش میداشتیم عالی میشد
در حال حاظر حتی وزن 900 هم برای title ها کافی نیست و مجبورم از یه فونت دیگه برای سرتیتر ها استفاده کنم

وزن 900 فونت وزیر مشابه به وزن 700 فونت ایران یکان هست و نمیتونه به اندازه اون _**thicc**_ بشه

**Comment by ShahriarKh** [comment]
#134

**Comment by rastikerdar** [comment]
ممنونم برای این ایشو
وزن‌های ضخیم نسخه جدید یعنی وزیرمتن یک مقدار جزئی ضخیم‌تر شدند. از صفحه زیر می‌تونید بررسی کنید. البته نسخه فوق سنگین هم می‌تونه مناسب باشه.
https://rastikerdar.github.io/vazirmatn/fa/lab

ممنونم @ShahriarKh پس من این ایشو رو به دلیل شبیه بودن می‌بندم تا از اونجا پیگیری بشه.
