### ISSUE TITLE
Suggest for Edits in some letters

### ISSUE THREAD

**Issue by ulaima** [rastikerdar/vazirmatn#226]
@rastikerdar
I think the half circle in ل ن س and ص is a little big
and ي letter need some adjustments
and i think the line in the bottom in letter ك is too long

Thank you for your work

**Comment by rastikerdar** [comment]
I improved those letters in version Vazirmatn 32, hope you like it:
https://github.com/rastikerdar/vazirmatn/releases

You can test and compare it with old Vazir:
https://rastikerdar.github.io/vazirmatn/ar/lab

Thanks
