### ISSUE TITLE
"أ" not show correctly 

### ISSUE THREAD

**Issue by X7md** [rastikerdar/vazirmatn#229]
![image](https://user-images.githubusercontent.com/54203033/149315257-6acc23df-4006-4049-a7de-48a5c8b4690d.png)

"أهلًا"

![image](https://user-images.githubusercontent.com/54203033/149315501-858ee198-876a-4666-a880-4b92621f5f5e.png)

**Comment by X7md** [comment]
I notice that just with windows...
But android show it correctly 😅...



![Screenshot_20220113-134957_Chrome](https://user-images.githubusercontent.com/54203033/149316682-c7b10abf-d6b0-4e0c-afbf-45c7f9d657d2.jpg)

"أن"

**Comment by X7md** [comment]
Any suggestions to workaround with this issue?

Preview: git.x7md.net

issue:
أ 
Not showing ء
Correctly.

OS: Windows 11

Browser:

Chrome & Firefox.

**Comment by rastikerdar** [comment]
Thanks for this issue. This is a bug and will be fixed in the next version.
