### ISSUE TITLE
Renaming and Restructuring (discussion)

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazirmatn#230]
مسیر پروژه داره دچار تغییراتی میشه که در ادامه آمده. اگر نظری دارید ممنون میشم بیان بفرمایید.

## New name
من تصمیم گرفته‌ام در نسخه جدید، نام این پروژه رو تغییر بدم و برای «وزیر» پسوندی بگذارم (فعلا یک چیزی انتخاب کرده‌ام). این نسخه جدید تغییرات زیادی داره و حجم بسیار زیادی کار روش صورت گرفته و تحول و به‌روزرسانی بزرگ و فصل جدیدی برای وزیر محسوب میشه. نکته دیگه اینکه نسخه‌های مختلفی از وزیر بین همه پخش شده و توی سایت‌ها یا کانال‌ها و ... اغلب نسخه‌های قدیمیِ چند سال پیش در دسترسه و مردم اطلاع ندارند که فونت هم مثل نرم‌افزارهای دیگه آپدیت میشه یا تغییر میکنه. پس عملا این آپدیت مهم وزیر با این نام فعلی کار بیهوده‌ای به نظر می‌رسه. همچنین چون ساختار پروژه کاملا تغییر می‌کنه در نتیجه برای کسانی که برنامه‌هاشون رو با نام فعلی آپدیت می‌کنند مشکل‌ساز خواهد بود.
یه نکته اینکه خوشبختانه گیت‌هاب تمام درخواست‌ها به آدرس فعلی رو به آدرس جدید هدایت خواهد کرد. البته یک راه هم این بود که یک مخزن و آدرس جدید ساخته بشه که خب نمیشد محتویات مخزن وزیر (سوابق و ایشوها و ...) رو به اونجا منتقل کرد.

## New address (Domain)
پروژه دارای دامین اختصاصی خواهد شد. این به ویژه در زمانی که احیانا گیت‌هاب ما رو تحریم کنه یا هر مشکلی دیگری در دسترسی به گیت‌هاب پیش بیاد باعث میشه پروژه همچنان در دسترس بمونه. همچنین باعث میشه که پروژه خودش صاحبِ خانه و هویت بشه و در جستجو‌های با نام خودش احتمالا در رتبه نخست قرار بگیره.

## New structure
ساختار پروژه از  ابتدا بازنگری شده. اسکریپت‌ها تغییر کرده‌اند. اما همچنان ساختار نهایی یک چالش است. می‌توان بر اساس ساختاری که گوگل ملزم می‌کنه این شکلی بسازیمش [Upstream Repo Structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repos):
```
.
├── AUTHORS.txt
├── CONTRIBUTORS.txt
├── OFL.txt
├── README.md
├── documentation
│   ├── readme-images.jpg
│   └── promo.png
├── fonts
│   ├── ttf
│   │   └── FontFamily-Regular.ttf
│   └── variable
│       └── FontFamily-[wdth,wght].ttf
├── sources
│   ├── FontFamily-sources.ext
│   └── build.sh
├── requirements.txt
└── .gitignore
```
منظور من به ویژه فولدر فونتز است. محتوای این پوشه برای اونها معمولا تکرار میشه اما برای ما ایرانی‌ها که انواع خروجی متفرقه فونت داریم یک مقداری فرق می‌کنه. پیشنهاد خودم اینه:

```
├── fonts
│   ├── ttf
│   │   └── FontFamily-Regular.ttf
│   ├── woff2
│   │   ├── FontFamily-font-face.css
│   │   └── FontFamily-Regular.woff2
│   ├── variable
│   │   └── FontFamily-[wdth,wght].ttf
│   └── misc
│       ├── Farsi-Digits
│       │   ├── ttf
│       │   │   └── FontFamily-FD-Regular.ttf
│       │   └── woff2
│       │       ├── FontFamily-FD-font-face.css
│       │       └── FontFamily-FD-Regular.woff2
│       ├── Non-Latin
│       │   ├── ttf
│       │   │   └── FontFamily-NL-Regular.ttf
│       │   └── woff2
│       │       ├── FontFamily-NL-font-face.css
│       │       └── FontFamily-NL-Regular.woff2
│       ├── Round-Dots
│       │   ├── ...
│       ...
```
تمام  ساختار فولدر فونتز مجددا در پوشهٔ «نقطه‌های گرد» تکرار میشه. همچنین نمیدونم فایل سی‌اس‌اس رو توی پوشه جدا بزارم یا توی همون فولدر تایپ
woff2
شاید بهتر باشه جدا بشه:

```
│   ├── ttf
│   │   └── FontFamily-Regular.ttf
│   ├── woff2
│   │   └── FontFamily-Regular.woff2
│   ├── css
│   │   └── FontFamily-font-face.css
```

## New website
من در حال نوشتن وبسایت با نکست‌جی‌اس هستم که توسعه‌اش راحت‌تر بشه اما باید برای پیاده‌سازی آن راه‌حل ساده و معقولی انتخاب کنم.  از جمله:
- محل قرار گیری فایل‌های سورس وبسایت و محل پارک دامین (مخزن فعلی یا یک مخزن جداگانه یا پوشه جداگانه یا برنچ مجزا یا ...)
- فرآیند گرفتن خروجی استاتیک و محل قرار گیریشون

**Comment by zoghal** [comment]
با توجه به اینکه می‌دونم دقیقا دچار چه ابعاد مشکلاتی هستی برای اینکار، پیشنهاد می‌کنم یک گپ صوتی در اینباره باهم داشته باشیم تا بتونیم اولیویت ها رو مشخص کنیم. چون تایپ کردن و بحث کردن پیرامون این موضوع یکمی زمانگیر هست.

اما پیشنهاد من:
> منظور من به ویژه فولدر فونتز است. محتوای این پوشه برای اونها معمولا تکرار میشه اما برای ما ایرانی‌ها که انواع خروجی متفرقه فونت داریم یک مقداری فرق می‌کنه. پیشنهاد خودم اینه:

فکر می‌کنم تیم گوگل با این موضوع(ساختار پروژه) مشکل داشته باشند. من پیشنهاد می‌دم شما دوتا مخزن داشته باش:
-  یکی مثلا به اسم vazir-int که از  ساختار گوگل تبعیت می‌کند و مخزن اصلی محسوب می‌شود.
- و یکی به اسم  vazir-ir  که فورک شده از مخزن  vazir-int است. در این مخزن براحتی می‌تونی ساختاری که نیاز‌های ایرانیان رو پشتیبانی می‌کند را بسادگی اعمال نمایید.

**Comment by rastikerdar** [comment]
به نکته خوبی اشاره کردید چون احتمالا ایراد میگیرن به این ساختار. البته چرا دو تا مخزن! فولدرشون رو جدا می‌کنم. توی فولدر فونتز عینا همون ساختار الزامی گوگل رو پیاده می‌کنم و در یک فولدر مجزا در ریشهٔ مخزن، فایل‌های متفرقه رو قرار می‌دم. اینطوری هم گوگل راضی میشه هم ما! 👍
```
├── fonts
│   ├── ttf
│   │   └── FontFamily-Regular.ttf
│   └── variable
│       └── FontFamily-[wdth,wght].ttf
├── misc
│   ├── Farsi-Digits
│   │   ├── ttf
│   │   │   └── FontFamily-FD-Regular.ttf
│   │   └── woff2
│   │       ├── FontFamily-FD-font-face.css
│   │       └── FontFamily-FD-Regular.woff2
│   ├── Non-Latin
│   │   ├── ttf
│   │   │   └── FontFamily-NL-Regular.ttf
│   │   └── woff2
│   │       ├── FontFamily-NL-font-face.css
│   │       └── FontFamily-NL-Regular.woff2
│   ├── Round-Dots
│   │   ├── ...
│   ...

**Comment by ghaznavipc** [comment]
خوشحالم که قراره پیشنهادم درمورد ایجاد یه مدل فونت وزیر که نقاطش گرد هست قراره توی این نسخه‌ی جدید پیاده‌سازی بشه :)
یه سوال برام پیش اومد. چرا باید فونت به دو قسمت یکی برای ایرانی‌ها و یکی برای گوگل‌داکز تقسیم بشه؟ برای اینه که آزادی عمل موقع تغییر و بروزرسانی بالاتر بره؟ گوگل اجازه‌ی بروزرسانی آزادانه برای تغییر یا رفع عیب به ناشر اصلیش نمی‌ده؟
دلیل انتخاب کلمه‌ی وزیر برای اسم این فونت رو نمیدونم تا بتونم پیشنهاد بهتری بدم ولی نظرتون چیه برای اسم جدید از ترجمه‌های انگلیسیِ وزیر استفاده کنید.
مثل: Vizier, Wazir, minister
اینجوری هم اسم تغییر کرده و هم تغییر نکرده! :)))
و با قبلی اشتباه نمیشه. شاید حتی برای متفاوت بودن توی فارسی از فینگلیش عبارت minister که میشه مینیستر استفاده کرد؟

**Comment by ghaznavipc** [comment]
یا استفاده از مترادف‌های فارسیِ وزیر.
یکیش فرزین بود که یه فونت دیگه با همین نام ساخته شده.
ولی مثلا کلمه‌ی **دستور** هم مترادفی از وزیر هست و در عین حال فونتی با این اسم ساخته نشده.
البته میشه از همون vazir که فرمودید با یه چیزی بعد یا قبلش استفاده کنید و خیلی قضیه عجیب یا وقت‌گیر و بی‌خود نباشه و هم اسم اصلی روش بمونه و هم متوجه بشیم که این جدیدتره. مثل b koodak که بعد ir koodak اومد.
شاید این هم مثلا بشه sr_vazir که sr مخفف حرف اول صابر راستی‌کرداره :)
یا مخفف‌تر r vazir
و هر فونت دیگه‌ای که طراحی و توسعه میدید همین حرف اول توش قرار داشته باشه. که خوبیش اینه که هم مخفف اسمتون روشه و هم توی جستجوی فونت‌ها موقع طراحی و غیره، (چون به ترتیب حروف نشون داده میشن) تمام فونت‌هاتون کنار هم قرار میگیرن.

**Comment by rastikerdar** [comment]
ممنونم برای پیشنهادتون. بلی توی نسخه جدید فونت نسخه نقطه گرد هم اضافه شده. به نظر خودم هم جالب شده.
در مورد اسامی هم که فونت دیگه‌ای در کار نیست. اون قبلی‌ها که تعطیل شدند. فعلا برای وزیر هم یک پسوندی انتخاب کرده‌ام والبته قطعا انگلیسی نیست. معمولا انتخاب اسم حالا چه اصلی و چه فرعی یکی از چالش‌های سخت کار هست.

**Comment by zoghal** [comment]
> به نکته خوبی اشاره کردید چون احتمالا ایراد میگیرن به این ساختار. البته چرا دو تا مخزن! فولدرشون رو جدا می‌کنم. توی فولدر فونتز عینا همون ساختار الزامی گوگل رو پیاده می‌کنم و در یک فولدر مجزا در ریشهٔ مخزن، فایل‌های متفرقه رو قرار می‌دم. اینطوری هم گوگل راضی میشه هم ما! 👍
> 
> ```
> ├── fonts
> │   ├── ttf
> │   │   └── FontFamily-Regular.ttf
> │   └── variable
> │       └── FontFamily-[wdth,wght].ttf
> ├── misc
> │   ├── Farsi-Digits
> │   │   ├── ttf
> │   │   │   └── FontFamily-FD-Regular.ttf
> │   │   └── woff2
> │   │       ├── FontFamily-FD-font-face.css
> │   │       └── FontFamily-FD-Regular.woff2
> │   ├── Non-Latin
> │   │   ├── ttf
> │   │   │   └── FontFamily-NL-Regular.ttf
> │   │   └── woff2
> │   │       ├── FontFamily-NL-font-face.css
> │   │       └── FontFamily-NL-Regular.woff2
> │   ├── Round-Dots
> │   │   ├── ...
> │   ...
> ```

چرا دو تا مخزن؟! برای اون موقعی که تیم گوگل ممکنه به همین ساختاری که گفتی هم ایرادهای عجیب و غریب بگیره :))

**Comment by rastikerdar** [comment]
> چرا دو تا مخزن؟! برای اون موقعی که تیم گوگل ممکنه به همین ساختاری که گفتی هم ایرادهای عجیب و غریب بگیره :))

اون موقع معلوم میشه که گوگل کلا با این فونت مشکل داره :)

**Comment by morezafard** [comment]
برای انتخاب پسوند میشه از اسامی وزرای صاحب نام در تاریخ ادبیات استفاده کرد. مثل: خواجه نظام الملک، حسنک یا خاندان برمکیان. وزیر حسنک شاید نام جالبی نباشه اما برای اکثر افراد آشناست به خصوص اینکه در کتاب ادبیات دوران دبیرستان درسی رو به حسنک وزیر اختصاص دادند. اما پیشنهاد من وزیر_برمکی(Vazir_Barmaki) ست.

**Comment by mehrali** [comment]
برای نام فونت، پسوندهای پیشنهاد‌ی زیر را هم داشته باشید:
پارس Pars - کبیر Kabir - آریا Aria - کارا Kara - یکتا Yekta- اعظم ‌‌Aezam- پرسپولیس Persepolis

**Comment by mparvazi** [comment]
با سلام
این فونت توسط کاربرانی که سایتشون از اسکریپت عربی استفاده میکنه مورد استفاده قرار گرفته و فقط مورد استفاده ایرانی ها نیست.
بنابراین در نامگذاری باید به این مورد توجه کرد:

**Vazir is a Persian/Arabic font**
