### ISSUE TITLE
Adding LICENSE file at root

### ISSUE THREAD

**Issue by mparvazi** [rastikerdar/vazirmatn#232]
Hello,

The [webpack-license-plugin](https://github.com/codepunkt/webpack-license-plugin) uses `LICENSE` file for reading license content.

The output with current structure:

![Screenshot from 2022-02-26 17-42-24](https://user-images.githubusercontent.com/85633460/155846316-767b805c-0591-4c3d-8d1d-7cdb4339837f.png)

So I tried to rename `OFL.txt` to `LICENSE`:

![Screenshot from 2022-02-26 17-45-02](https://user-images.githubusercontent.com/85633460/155846413-213a26a6-5c6e-43c1-8b71-9ab7308a0087.png)

**Comment by mparvazi** [comment]
سلام،
در حال به روز رسانی استفاده از این فونت در پرستاشاپ هستیم.
آیا ممکن است در آینده نزدیک دوباره ساختار تغییر کنه؟
یا اینکه میتونیم الان به روز رسانی رو انجام بدیم؟
https://github.com/PrestaShop/PrestaShop/pull/27611

**Comment by rastikerdar** [comment]
سلام
شاید بهتر باشه یکی دو روز صبر کنید تا اگر مشکلی هم بود رفع بشه. البته ساختار طبق الزام گوگل‌فونت به این شکل تغییر پیدا کرده و فکر نکنم دیگه تغییر کنه. اگر اشکالی دیدین ممنون میشم گزارش کنید.

**Comment by mparvazi** [comment]
@rastikerdar 

PrestaShop 8.0
vazirmatn@32.0.0

![Screenshot 2022-03-09 at 00-17-30 مدیریت مشتریان • vazir](https://user-images.githubusercontent.com/85633460/157322549-e016fd58-a6db-4919-84d9-fefb09df318e.png)

![Screenshot 2022-03-09 at 00-16-42 محصول • vazir](https://user-images.githubusercontent.com/85633460/157322581-669e5d4e-ef8f-4125-bffb-72a59bd510cc.png)

**Comment by rastikerdar** [comment]
حس می‌کنم به نمای پنلتون خوب نشسته. حالا بیشتر بررسی کنید.

**Comment by mparvazi** [comment]
با سلام و عرض خسته نباشید
به نظر میرسه ساختار فونت تایید شده و الان میتونیم از ساختار فعلی برای وب پک استفاده کنیم.

**Comment by rastikerdar** [comment]
سلام
البته هنوز تایید نهایی نشده ولی به نظر میرسه مشکلی نباشه.
