### ISSUE TITLE
علت تغییر نام

### ISSUE THREAD

**Issue by xmha97** [rastikerdar/vazirmatn#235]
با سلام
می‌خواستم بدونم علت تغییر نام فونت وزیر به وزیرمتن چیه؟
این فونت با این نام شناخته شده است و قطعا خیلی‌ها از جمله خودم فکر خواهند کرد که وزیرمتن نسخه‌ی مد شده‌ی وزیر است.
همچنین این تغییر باعث خواهد شد که پکیج شکلاتی که فونت را نصب می‌کند به شکل اتوماتیک بسته را آپدیت نکند.

**Comment by rastikerdar** [comment]
سلام
درست می‌فرمایید. در این صفحه توضیح داده‌ام:
https://rastikerdar.github.io/vazirmatn/fa/docs/HELP-fa

بهتره که وزیر رو فراموش کنیم. احتمالا برای مخازنِ نگهداری باید پروژه جدید ثبت کرد. برای npm هم پکیج جدید ثبت شد.

**Comment by ALipAkrohk** [comment]
> با سلام می‌خواستم بدونم علت تغییر نام فونت وزیر به وزیرمتن چیه؟ این فونت با این نام شناخته شده است و قطعا خیلی‌ها از جمله خودم فکر خواهند کرد که وزیرمتن نسخه‌ی مد شده‌ی وزیر است. همچنین این تغییر باعث خواهد شد که پکیج شکلاتی که فونت را نصب می‌کند به شکل اتوماتیک بسته را آپدیت نکند.

درمورد وزیر نیست این متن من درمورد پکیج منیجریت ( یه پیشنهاد ) بجای اون از winget یا scoop استفاده کن موارد بهتری هستن.
موفق باشی ( به امید روزی که گنو/لینوکسی شدی )

**Comment by xmha97** [comment]
https://github.com/rastikerdar/vazir-code-font
فونت "وزیر کد" هم در آینده میشه "وزیرمتن کد" ؟

**Comment by xmha97** [comment]
> درمورد وزیر نیست این متن من، درمورد پکیج منیجرتِ ( یه پیشنهاد ) بجای اون از winget یا scoop استفاده کن موارد بهتری هستن.
> موفق باشی ( به امید روزی که گنو/لینوکسی شدی )

سلام، ممنون از پیشنهادتون
بله scoop بهتر است چرا که به دسترسی ادمین نیاز ندارد و تحت یوزر کار میکند.
راستی یه ماهه که لینوکس هم نصب کردم.

**Comment by rastikerdar** [comment]
> فونت "وزیر کد" هم در آینده میشه "وزیرمتن کد" ؟

خیر. پرونده اون هم مثل بقیه خیلی وقته بسته شده.
