### ISSUE TITLE
[Website Lab] Add `min-width` to TextArea

### ISSUE THREAD

**Issue by X7md** [rastikerdar/vazirmatn#236]
https://github.com/rastikerdar/vazirmatn/blob/bc97260aab658fbb2ff442e244caa68b992f31df/website/src/features/lab/TextArea.tsx#L76-L82

```patch
 <div 
   contentEditable={contentEditable} 
   suppressContentEditableWarning={true} 
   spellCheck="false" 
+ style={{minWidth: 10rem}}
   dir="auto" 
   dangerouslySetInnerHTML={{ __html: text.replace(/\n/g, "<br>") }} 
 /> 
```

to improve User Experience when user delete all text, and click away, text cursor `|` don't show without click <kbd>Tab</kbd> to focus text div element, adding `mix-width` will allow user to back to the textArea using mouse or by click when using mobile phone.

maybe there is another workaround to fix this.

![image](https://user-images.githubusercontent.com/54203033/157317185-3ffd4a74-6006-4076-85bc-b92b26e131a4.png)

**Comment by rastikerdar** [comment]
Thank you @X7md. Fixed the issue.
