### ISSUE TITLE
درخواست نسخه ui با نقطه گرد

### ISSUE THREAD

**Issue by Monirzadeh** [rastikerdar/vazirmatn#240]
باسلام لطفا در صورت امکان نسخه Vazirmatn UI ورژن با نقطه گرد را هم اضافه کنید.
با تشکر

**Comment by sepehr-brj** [comment]
نسخه UI با نقطه گرد توی این مسیره:
Round-Dots > misc > UI

**Comment by Monirzadeh** [comment]
در نسخه موجود در AUR این فونت موجود است؟ چون در لیست فونت‌ها این مورد نمایش داده نمی‌شود و تنها Vazirmatn NL وجود دارد.

**Comment by rastikerdar** [comment]
@molaeiali شاید راهنمایی کنند

**Comment by molaeiali** [comment]
تا جایی که یادمه همه رو اضافه کردم، ولی شاید جا افتاده باشه، بررسی می‌کنم

**Comment by molaeiali** [comment]
انجام شد، ولی شاید در آینده یه پکیج جدا بذارم برای RD خیلی تعداد زیادی فونت شد توی یک بسته

ایشو ولی میتونه کلوز بشه (از اول هم البته ایشوی فونت نبود باید توی خود AUR مطرح میشد)
