### ISSUE TITLE
Issue یا Discussions?

### ISSUE THREAD

**Issue by ShahriarKh** [rastikerdar/vazirmatn#243]
برای پیشنهاد دادن در مورد فونت و ... از کدوم استفاده کنیم؟

**Comment by rastikerdar** [comment]
فکر کنم مباحث گفتگو محور یا پرسش و پاسخ به Discussions مربوط میشه. اما خب از اونجایی که میشه ایشو رو هر زمان به Discussions تبدیل کرد مشکلی نیست. شما در ایشو مطرح کنید.
