### ISSUE TITLE
مشکل در کرنینگ حرف ر یا ک در کورل

### ISSUE THREAD

**Issue by PAPIONbit** [rastikerdar/vazirmatn#245]
سلام و درود به شما برادر راستیکردار
به نظرم میرسه کرنینگ حرف "ر" یا "ک" در کورل (به دلیلی که نتونستم پیداش کنم) مشکل داره،

![image](https://user-images.githubusercontent.com/47592258/158159508-df7118dd-da71-4432-94b6-7871edb53426.png)

البته این مشکل با اندازه بسیار کمتری برای ترکیب حروفی مثل "د" + "ک" هم هست.

Win10 LTSC 2021
CorelDraw 2018 - 2021

VazirMatn 32

**Comment by rastikerdar** [comment]
سلام. ممنونم برای این ایشو. به نظر میاد این به دلیل شیوه کرنینگ در وزیرمتن هست که در دو فونت دیگر متفاوت می‌باشد. من مجبور به انتخاب ابن شیوه شدم تا در برنامه‌های ادوبی مثل اکس‌دی هم درست کار کنه. بگردید شاید گزینه‌ای در برنامه کورل وجود داره که بشه kerning رو غیر فعال کرد. البته جالبه که سمت چپ داره درست نشون میده. فعلا نمی‌تونیم این مورد رو تغییر بدیم مگر اینکه به طور کلی در آینده در کرنینگ این فونت تجدیدنظر صورت بگیره یا راه مناسبی پیدا بشه.

**Comment by aminabedi68** [comment]
سلام.
متأسفانه برای این مشکل نمیشه کاری کرد، ایراد از خود کورل هست.(تو اینترنت جستجو کنین) تو همۀ فونتا این اتفاق میوفته اما میزانش بستگی به مقادیر کرنینگ داره. توی تصویر بالا در مورد ایران‌سنس هم این اتفاق افتاده(به اتصال «شر» دقت کنین) در مورد فونت یکان چون اتصالات مسطح هست دیده نمیشه.
من در چند مورد به درخواست مشتری این مشکل رو سعی کردم برطرف کنم.(البته اصلاً توصیه نمی‌کنم) 2 روش وجود داره:
1- تمام ترکیبات کرنینگ رو تبدیل به لیگیچر کنیم(که تبدیل تمام حالات محتمل کار خیلی مشکلی هست)
2- از حروف جایگزین با مرز سمت راست و چپ کمتر استفاده کنیم(توی فونتای هندسی این روش حتی راحت‌تر از خود کرنینگ هست)
روش‌های سخت‌تری هم وجود داره، مثلا استفاده از mark به جای کرنینگ... ولی به هر حال این مشکل کورل هست و باید از طرف خود کورل برطرف بشه.

**Comment by rastikerdar** [comment]
پس مشکل از طرف خود کورل هست و فونت‌ها بی‌تقصیرند. من با اجازه ایشو رو می‌بندم.
