### ISSUE TITLE
تغییر اسم

### ISSUE THREAD

**Issue by babakfp** [rastikerdar/vazirmatn#246]
سلام
این همون فونت وزیره؟ چرا اسمشو تغییر دادین؟!😐

**Comment by rastikerdar** [comment]
#235 ایشو مشابه
سلام
وزیرمتن نسبت به وزیر در همه ابعاد تغییرات گسترده داشته. درواقع متحول شده. مثلا نامگذاری فایل‌های متفرقه همگی تغییر کرده که در بروزرسانی مشکل‌آفرین بود. این تغییرات همگی اجباری بود.
از طرفی بسیاری هنوز از نسخه‌های بسیار قدیمی مربوط به چهار پنج سال پیش استفاده می‌کنند و تمایل و حتی اطلاعی از به بروزرسانی ندارند چون اغلب از سایت‌های دانلود فونت رایگان دریافت کرده‌اند. حتما ادامه رویه فعلی کار بیهوده‌ای بود.

توضیحات بیشتر در مورد تغییر نام:
https://rastikerdar.github.io/vazirmatn/fa/docs/HELP-fa

فهرست تغییرات:
https://github.com/rastikerdar/vazirmatn/blob/master/CHANGELOG.md
