### ISSUE TITLE
مشکل نیم‌فاصله در ورد

### ISSUE THREAD

**Issue by kokabi1365** [rastikerdar/vazirmatn#249]
<div dir="rtl">
در نرم‌افزار ورد بعد از نوشتن نیم‌فاصله - چه با shift + space و چه با ctrl+shift+2 - فونت به صورت خودکار عوض می‌شه. این اتفاق برای فونت‌های دیگر نمی‌افته. در نسخهٔ قبلی وزیر این مشکل وجود نداشت. برای اولین بار در وزیرمتن با این مشکل مواجه شدم.

![Animation](https://user-images.githubusercontent.com/44271870/159157045-ea417a01-2794-4052-badf-b9e7e1dfd69f.gif)

</div>

**Comment by rastikerdar** [comment]
ممنونم برای این ایشو.
اگر اشتباه نکنم تنها آفیس با این قضیه مشکل داره. حتی توی نوت‌پد یا وردپد هم این مشکل نیست. خوشبختانه شما گزارش کردید؛ چون من آفیس ندارم، متوجه‌اش نمی‌شدم. یک نسخه جدید برای اضافه کردن گلیف‌های مربوطه منتشر شد. امیدوارم مشکل رفع شده باشه.
https://github.com/rastikerdar/vazirmatn/releases

**Comment by kokabi1365** [comment]
<div dir="rtl">
ماشاءالله به این سرعت.
الان تست کردم، مشکل  حل شده.
بله در نت‌پد و وردپد این مشکل وجود نداشت. فقط در ورد وجود داشت و فقط برای این نسخه از وزیر.
البته برام عجیبه چطور در تست‌هاتون، آفیس رو که یک نرم‌افزار بسیار ضروری در حوزهٔ نشر هست در نظر نگرفتید. تقریباً هر کسی در ویندوز با نوشتن سروکار داره از این نرم‌افزار استفاده می‌کنه!
</div>

**Comment by rezad1393** [comment]
> ماشاءالله به این سرعت.
> 
> الان تست کردم، مشکل حل شده. بله در نت‌پد و وردپد این مشکل وجود نداشت. فقط در ورد وجود داشت و فقط برای این نسخه از وزیر. فقط برام عجیبه شما چطور در تست‌هاتون، آفیس رو که یک نرم‌افزار بسیار ضروری در حوزهٔ نشر هست در نظر نگرفتید. تقریباً هر کسی در ویندوز با نوشتن سروکار داره از این نرم‌افزار استفاده می‌کنه!

احتمال داره که از libreofflice استفاده میکنه
