### ISSUE TITLE
مشکل در وریبل فونت (نسخۀ نقطه گرد)

### ISSUE THREAD

**Issue by alimanian** [rastikerdar/vazirmatn#252]
سلام
در نسخه Variable Font RD زمانی که کاراکتر "ث" به عنوان اولین کاراکتر استفاده بشه به صورت زیر نمایش داده میشه. 

![Screenshot 2022-04-01 195213](https://user-images.githubusercontent.com/65087900/161294778-d3d91513-40b1-4037-9ed1-2d3aa62eaad9.jpg)
![Screenshot 2022-04-01 195241](https://user-images.githubusercontent.com/65087900/161294785-2ac99c7e-0d9d-492f-bdfc-a56bca68666c.jpg)

**Comment by rastikerdar** [comment]
سلام
ممنونم برای گزارش این ایراد مهم. در نسخه جدید برطرف شد. سپاس
https://github.com/rastikerdar/vazirmatn/releases

**Comment by rastikerdar** [comment]
اگر باز هم ایرادی دیدن ممنون میشم گزارش کنید
