### ISSUE TITLE
مشکل طولانی تر شدن متن نسبت به سایر فونت های استاندارد

### ISSUE THREAD

**Issue by amiNorouzi** [rastikerdar/vazirmatn#256]
طول متن در فونت وزیرمتن نسبت به سایر فونت های استاندارد خیلی بیشتره که اون رو به فونت های Mono شبیه کرده. این مشکل در نمایشگر موبایل بیشتر دیده میشه. مخصوصا در طراحی UI.  این مشکل برای انگلیسی هم هست اما فقط در کاراکتر اسپیس. من در یک اپلیکیشن چند زبانه از وزیر استفاده کردم اما برای تنظیم کردن اندازه متن به گونه ای که هم برای فارسی و هم برای انگیسی مناسب باشه به مشکل خوردم.

![image](https://user-images.githubusercontent.com/71645551/161447767-496ac195-eca1-4f0d-8b82-346b8430aa54.png)
در این تصویر اندازه و font weight هر دو خط برابر است.

**Comment by rastikerdar** [comment]
خب هر فونتی اندازه و سبک مختص به خودش رو داره. اگر با سایر فونت‌های عربی یا فارسی امتحان کنید می‌بینید برخی بزرگتر از وزیرمتن و برخی کوچکتر هستند. شما می‌تونید فاصله بین واژه‌ها رو کم یا زیاد کنید. مثلا در وب:
```css
.class {
    word-spacing: -2px;
}
```

**Comment by amiNorouzi** [comment]
درسته، اما در همه جا امکان تنظیم word-spacing نیست علاوه بر اون حتی در این صورت کلمات انگلیسی بیش از حد به هم نزدیک میشن. در واقع مشکل اصلی هماهنگ نبودن با انگلیسی در اپ های دو زبانه هست. اگر فقط فارسی رو در نظر بگیریم همه چیز رو میشه متناسب با خط فارسی تنظیم کرد و مشکلی نخواهد بود.

**Comment by rastikerdar** [comment]
بهتره که UI خودتون رو انعطاف‌پذیر طراحی کنید تا هر موقع زبان یا فونت رو عوض می‌کنید به مشکل بر نخورید یا اینکه از فونت‌های فشرده‌تر فارسی/عربی استفاده کنید. البته در لاتین فونت‌هایی داریم که نسخه فشرده دارند اما در فارسی به دلیل اتصال حروف این کار سخت یا غیر ممکن است. من با اجازه ایشو رو می‌بندم. اگر سوالی داشتید بپرسید.
