### ISSUE TITLE
از دست دادن شکیل بودن فونت

### ISSUE THREAD

**Issue by mimsadAlef** [rastikerdar/vazirmatn#260]
در فونت وزیر متن حالت شکیل بودن فونت از بین رفته و به نظرم از زیباییش کاسته شده دلیلش چی بوده

احتمالم داره که برای من این طور نشان داده شود ولی در حالت نرمال یا عادی این رو حس می کنم اما در حالت سیاه و بولد خیر

**Comment by rastikerdar** [comment]
اگه براتون امکان داره یک تصویر از آنچه که می‌بینید بگذارید تا من بتونم دقیقا متوجه منظور شما بشم. توی این صفحه می‌تونید هر دو فونت وزیرمتن و وزیر قدیمی رو با هم مقایسه کنید:
https://rastikerdar.github.io/vazirmatn/fa/lab

**Comment by rastikerdar** [comment]
اگر توضیحی دارید ممنون میشم بیان بفرمایید، در غیر اینصورت ایشو رو ببندیم.

**Comment by mimsadAlef** [comment]
یکم آزمایش کردم نظرم برگشت
احتمالا به دلیل عادت چشم به فونت وزیر قدیمی بوده
