### ISSUE TITLE
Request to add glyphs from Jawi letters

### ISSUE THREAD

**Issue by WanAhmadShahmi98** [rastikerdar/vazirmatn#262]
The letters peculiar to Jawi (apart of Arabic and Persian characters) are as listed below, each with Unicode codepoints and names in brackets:
1.	‎ٴ
		(**U+0674** • ARABIC LETTER HIGH HAMZA)
3.	‎ڠ	
		(**U+06A0** • ARABIC LETTER AIN WITH THREE DOTS ABOVE)‎
5.	‎ڽ
		(**U+06BD** • ARABIC LETTER NOON WITH THREE DOTS ABOVE)‎
7.	‎ۏ
		(**U+06CF** • ARABIC LETTER WAW WITH DOT ABOVE)
9.	‎ݢ
		(**U+0762** • ARABIC LETTER KEHEH WITH DOT ABOVE)

**Comment by rastikerdar** [comment]
Thanks for this issue. All added in version 33.
https://github.com/rastikerdar/vazirmatn/releases
