### ISSUE TITLE
مشکل تفاوت در ارتفاع خط برای کاراکترهای لاتین

### ISSUE THREAD

**Issue by mparvazi** [rastikerdar/vazirmatn#264]
با سلام

وقتی کاراکترها به صورت کامل انگلیسی هستند ارتفاع خط متفاوت به نظر میاد (کمی بالاتر از حروف فارسی):
آیا باید به این صورت باشه؟ یعنی الویت با تراز بودن حروف فارسی است؟

<img src="https://user-images.githubusercontent.com/85633460/166097843-436332c4-c375-43fa-abba-6a2c384446f5.png" width="600">

## Vazirmatn
<img src="https://user-images.githubusercontent.com/2854834/165959080-cefb80bf-d740-46cb-af5c-b0dacdb22ead.png" width="900">

## Open sans
<img src="https://user-images.githubusercontent.com/2854834/165958977-45826d0f-6c2a-4625-ad70-dfeac690a9b3.png" width="900">

https://github.com/PrestaShop/PrestaShop/pull/28277#pullrequestreview-957810063

**Comment by babakfp** [comment]
لینک به این صفحه رو داری که آنلاین بشه دید؟ از لینکی که به پروژه دیگه دادی نتونستم لینکی به همین صفحه پیدا کنم. یه لینکی که مستقیم بره به این صفحه, یا حداقل به همراه یوزر و پسورد ورود به صفحه حساب کاربری...

**Comment by rastikerdar** [comment]
سلام
ممنونم برای این ایشو. در وزیرمتن فرقی بین حالت تمام انگلیسی و فارسی نیست. چون بخش قابل توجهی از حروف فارسی زیر خط کرسی قرار داره به نظر تراز میاد. دلیل تفاوت ارتفاع توی این ایشو آمده: #110
فکر می‌کنم در نسخه بعدی باید ارتفاع داخل فونت رو از بالا زیاد کنم تا نوشته‌ها پایین‌تر بیان.
البته اگر فونت اول رو لاتین مورد نظرتون که حروف فارسی/عربی نداره بگذارید و ثانوی رو وزیرمتن احتمالا مشکل حل بشه چون به ارتفاع فونت لایتن بسنده می‌کنه. (هرچند که در زمینه علائم و فاصله اولویت با فونت لاتین میشه):
```css
body {
    font-family: latin-font-name, Vazirmatn;
}
```
به جز فونت‌های خود ویندوز اگر فونتی می‌شناسید که در این مورد مشکلی نداره نام ببرید تا بررسیشون کنم ببینم میشه برای وزیرمتن هم انجام داد یا خیر.

**Comment by mparvazi** [comment]
با قالب bootstarp 5 یک تست ساده انجام دادم
با تغییر فونت بین sans-serif و وزیر ارتفاع تغییر میکنه

https://user-images.githubusercontent.com/85633460/166120776-7a91b15d-49b1-46d5-b7fb-c81e1f9bba5d.mp4

سعی میکنم با فونت ها دیگه هم تست کنم

**Comment by mparvazi** [comment]
فقط تو این حالت مشکل حل میشه:
`https://www.npmjs.com/package/@fontsource/roboto`

```
body {
    font-family: Roboto, Vazirmatn;
}
```

**Comment by mparvazi** [comment]
سلام
فونت های دیگه رو بررسی کردم
مشکلی که اینجا اشاره کردم برای فونت های انگلیسی/فارسی اجتناب ناپذیر هست.
با تشکر.

**Comment by rastikerdar** [comment]
پیشنهاد می‌کنم همانطور که برای عربی/فارسی برخی کارها از جمله راست به چپ کردن صفحه انجام میشه، برای تراز عمودی خطوط هم کاری انجام بشه. یعنی در حالت فارسی تنظیم عمودی با حالت انگلیسی تفاوت داشته باشه. راستش من راهی برای خود فونت پیدا نکرده‌ام اما اگر پیدا شد خبرتون می‌کنم. مانند:
```css
.rtl button span.icon {
    vertical-align: middle;
}
```
```css
.muirtl button span {
    align-self: baseline;
}
```
