### ISSUE TITLE
Monospaced version

### ISSUE THREAD

**Issue by AhmedElTabarani** [rastikerdar/vazirmatn#268]
هل يوجد نسخة [monospace](https://en.wikipedia.org/wiki/Monospaced_font) للخط؟

**Comment by rastikerdar** [comment]
No, there isn't. However there is a monospace version based on the old Vazir (about 6 years ago):
https://github.com/rastikerdar/vazir-code-font/releases

**Comment by AhmedElTabarani** [comment]
> No, there isn't. However there is a monospace version based on the old Vazir (about 6 years ago): https://github.com/rastikerdar/vazir-code-font/releases

I don't think It's still working any more، the link is not available or not correct

**Comment by AhmedElTabarani** [comment]
sorry, I was using the wrong link.
