### ISSUE TITLE
Merge with default font

### ISSUE THREAD

**Issue by behrooztahmasbi** [rastikerdar/vazirmatn#271]
این امکان هست فقط قسمت فارسی وزیر متن رو با فقط قسمت انگلیسی فونت دیفالت اوبونتو مرج کنیم؟
در واقع فونت سیستم همون Ubuntu regular باشه ولی فونت فارسیش (مثلا در نمایش اسم فولدر ها) وزیر متن باشه؟

**Comment by rastikerdar** [comment]
یک نسخه بدون حروف انگلیسی (None-Latin) در بسته فشرده وزیرمتن وجود داره که می‌تونید با هر فونت دلخواهی ترکیبش کنید. البته شاید اساسا نیازی به ترکیب نباشه و در اوبونتو بتوانید تعیین کنید فونت اصلی خود اوبونتو باشه و فونت فالبک یا ثانوی یا جایگزین (برای زمانی که حروف مورد نظر در فونت اصلی نباشه مثل فارسی) هم وزیرمتن باشه. در این صفحه عنوان سوال «چگونه می‌توانم در میزکارهای مبتنی بر Fontconfig (بیشتر سیستم عامل‌های Unix-like)، فونت پیش‌فرض را وزیرمتن قرار دهم؟» رو مطالعه بفرمایید شاید کمکتون کنه.
https://rastikerdar.github.io/vazirmatn/fa/docs/HELP-fa
