### ISSUE TITLE
Jawi letter ڽ forms issue

### ISSUE THREAD

**Issue by WanAhmadShahmi98** [rastikerdar/vazirmatn#272]
The letter ڽ (U+06BD, Arabic Letter Noon with Three Dots Above) has different dot position in initial and medial forms.
The three dots above should be moved below the Noon in initial and medial form, resembling the letter پ. Isolated form and final form of ڽ, both have three dots remain above Noon.

**Comment by rastikerdar** [comment]
I'm sorry, my mistake. Fixed in version 33.001
https://github.com/rastikerdar/vazirmatn/releases

![Screenshot at 2022-06-10 18-05-10](https://user-images.githubusercontent.com/3116038/173077281-39be3311-9502-4ec6-b451-3240070cab5d.png)

Please report any bugs you find.
Thanks
