### ISSUE TITLE
اعداد فارسی

### ISSUE THREAD

**Issue by vahidalvandi** [rastikerdar/vazirmatn#277]
آیا امکان نمایش اعداد با فونت فارسی است ؟

**Comment by rastikerdar** [comment]
اگر درست متوجه منظورتون شده باشم نسخه «تمام ارقام فارسی» یعنی Farsi-Digits رو در بسته کامل فونت در پوشه misc پیدا و نصب کنید. و یا برای صفحات وب از روش جدیدتری که در این صفحه آمده می‌تونید استفاده کنید (قسمت مربوط به ارقام رو مطالعه بفرمایید):
https://rastikerdar.github.io/vazirmatn/fa/docs/HELP-fa

**Comment by vahidalvandi** [comment]
درورد بر شما
