### ISSUE TITLE
ترکیب با دیگر فونت ها

### ISSUE THREAD

**Issue by SMAH1** [rastikerdar/vazirmatn#33]
وجود اسکریپتی که بتوان فونت وزیر را با دیگر فونت ها بخصوص 
DejaVu
یکپارچه کرد،بسیار کار را برای تولید فونت یکپارچه برای تمام گلیف ها راحت خواهد کرد

**Comment by rastikerdar** [comment]
با توجه به وریبل شدن وزیر/وزیرمتن و پیچیده‌تر شدن فرآیند ترکیب با فونت لاتین در حین تولید، امکان نوشتن این اسکریپت دشوارتره شده هرچند که فایل‌های غیر وریبل رو میشه به راحتی با سایر فونت‌ها ترکیب کرد. چه از طریق فونت‌فورج، چه [اسکرپیت](https://fonttools.readthedocs.io/en/latest/merge.html) و چه احتمالا ابزارهای آنلاین. با تشکر.
