### ISSUE TITLE
مشکل در محل اتصال دو حرف چسبان

### ISSUE THREAD

**Issue by javadft** [rastikerdar/vazirmatn#36]
<div dir="rtl" align="right">
قبلاً(در نسخه ۲ اگر اشتباه نکنم) مکشلی وجود داشت که در پی‌دی‌اف در بعضی بزرگنمایی‌ها محل اتصال بعضی حروف چسبان خالی بود.
ظاهراً در نسخه ۴.۱.۰ تغییراتی در این باره با عنوان «افزایش نواحی همپوشانی» انجام شده که مشکل مذکور رو حل کرده ولی مشکل دیگری ایجاد شده این که همون محل اتصال بد رندر میشه.

نمیدونم این مشکل به خاطر ابزار منه یا نه: ویندوز 7، پی‌دی‌اف ذخیره شده از ورد ۲۰۰۷ با افزونه پی‌دی‌اف آفیس، نمایش در نرم‌افزار ادوبی ریدر 8
</div>

![chasban](https://i.imgur.com/m6snAWD.png)

**Comment by rastikerdar** [comment]
متشکرم برای گزارش این خطا
اگر برایتان مقدور است بررسی بفرمایید یکی دو تا فونت دیگری که این اشکال در آنها جود ندارد یعنی هم بین حروف فاصله نمی‌افتد و هم در ناحیه اتصال به درستی رندر می‌شود در صورت نداشتن مشکل لایسنس اینجا قرار دهید یا لینک دهید تا بتونم با الگوگیری از آنها این نقیصه رو رفع کنم.

**Comment by javadft** [comment]
اکثر فونتهایی که من داشتم بیشتر مشکل خالی بودن رو داشتن. مشکل در بعضی فونتها خفیف و بود و اصلاً به چشم نمی‌اومد.
مثلاً [این نسخه نازنین](http://irfont.ir/post/103/free%20download%20b%20nazanin%2B%20font) این ایرادها رو نداشت. جالب اینکه خود فونت تاهوما ویندوز 7 هم این ایرادها رو نداشت
دو نسخه از زر و میترا هم داشتم که زیاد در این زمینه ایراد نداشتند
[Desktop.zip](https://github.com/rastikerdar/vazir-font/files/501552/Desktop.zip)

**Comment by zoghal** [comment]
@javadft درود بر شما
روی فونت های قدیمی نمیشه زیاد حساب باز کرد. لطفا برای اطمینان از صحت ابزارتان ممنون میشم یکبار هم این فونت رو چک کنید.
https://github.com/font-store/font-behdad

**Comment by rastikerdar** [comment]
#38
