### ISSUE TITLE
نمایان شدن نقاط اتصال حروف چسبان در رنگ های شفاف

### ISSUE THREAD

**Issue by alihaddadkar** [rastikerdar/vazirmatn#38]
با عرض سلام و خسته نباشید
در حالت عادی همه چیز درست هست اما در حالتی که رنگ نوشته کمی شفاف باشد نقاط اتصال حروف مشخص می شوند مانند تصویر زیر:
در ورژن ۳ همه چیز درست هست اما وقتی به ورژن ۴ آپیدت کردم این مشکل رو دیدم.

<img width="450" alt="screen shot 2016-11-03 at 6 53 27 pm" src="https://cloud.githubusercontent.com/assets/6142279/19973869/c4496b7e-a1fb-11e6-91a3-933d20278481.png">

**Comment by rastikerdar** [comment]
سلام و تشکر
حق با شماست. مشکل ورژن سه این بود که در برخی شرایط یا موقعیت ها (مثلا اندازه فونت) بین حروف اندکی فاصله می افتاد. توی اون نسخه من این مقدار ناحیه همپوشانی حروف رو بسیار کم گرفته بودم یعنی حدودا ده واحد. اما توی ورژن چهار تصمیم گرفتم این مشکل رو جبران کنم و به حدود ۸۰ واحد افزایش دادم. به نظر میاد مشکل فاصله افتادن بین حروف حل شده باشد اما حالا مشکلی که شما فرمودید جایگزین آن شده.

راهی که به ذهنم میرسه اینه که اگر برایتان امکان دارد به جای شفافیت توی رنگ ها از شفافیت اُپاسیتی استفاده کنید. با این شیوه اون ناحیه اتصال دیده نمیشه.
opacity: 0.7;

برای خودم هم سواله که چجوری میشه این مشکل رو حل کرد.

**Comment by alihaddadkar** [comment]
متاسفانه نمیتونم از اپاسیتی استفاده کنم مجبورم بیخیال شفافیت بشم.
ممنون از پاسختون 👍

**Comment by zoghal** [comment]
> برای خودم هم سواله که چجوری میشه این مشکل رو حل کرد.

با صبر کردن، این مشکل مربوط به شیپ انجین ها هست. به نظرم این هم پوشانی خیلی مسخره هست. باید این رو بیخیال بشند. هرچند یک سری کاربرد هم داره

**Comment by rastikerdar** [comment]
خوشبختانه این مشکل با کوچک شدن ناحیه همپوشانی تا حدود زیادی کاسته شده اگر چه کاملا برطرف نشده. در هر صورت تا خود انجین‌ها فکری برایش نکنند کاری از دست ما بر نمیاد. در این صفحه می‌تونید میزان شفافیت رو تست کنید:
https://rastikerdar.github.io/vazirmatn/fa/lab
با تشکر
