### ISSUE TITLE
اضافه کردن به گوگل فونت

### ISSUE THREAD

**Issue by Pro-Ton** [rastikerdar/vazirmatn#39]
با سلام و تشکر خواستم پیشنهاد بدم که در فونت‌ها رو در دایرکتوری فونت گوگل ثبت کنید تا قابل استفاده در مجموعه گوگل داکز و وب فونت گوگل شود.

ظاهرا باید فرم زیر پر شود
https://services.google.com/fb/forms/submitafont/

**Comment by zoghal** [comment]
@rastikerdar صابر جان من چندبار خواستم این رو مطرح کنم تو ایشو گروه فونت آزاد اما می‌دونستم بهداد اسفهبد جواب من رو نمیده. اگر امکانش هست این سوال رو بپرسی دقیقا برای درج در گوگل فونت باید چه شرایطتی از نظر پشتیبانی زبان و کاراکترست و .... داشته باشه.؟

**Comment by rastikerdar** [comment]
@Pro-Ton 
متشکرم برای این ایشو. راستش هم اینکه خودم فرصتی ندارم و هم اینکه فونت کامل نشده.

@zoghal احتمالا صفحه یا سندی هست که در موردش توضیح داده باشه. چون من اون فرم رو الکی
 پر کردم به امید اینکه بالاخره یه راهنمایی چیزی ببینم اما صرفا ثبت کرد و نوشت بعدا خودشون بررسی می‌کنند! هر چند که آقای اسفبهد توی ایشوی #29 برای نمونه به بیلد سیستم آقای خالد حسنی اشاره فرمودند.

@behdad
آقای اسفهبد عزیز عذرخواهی می‌کنم شما از شرایط اطلاعی دارید؟ جایی هست که در موردش توضیح داده باشه؟

**Comment by MYDavoodeh** [comment]
با سلام خدمت بزرگواران
بعد از چندین سال هنوز پیشرفتی در این مبحث صورت نگرفته؟

**Comment by rastikerdar** [comment]
راستش رو بخواین پیگیرش نیستم. مخزن رو باید تغییر بدم و از طرفی مکاتبه و پیگیری و این حرفا که در نهایت فکر نکنم با توجه به نیاز اغلب کاربران این فونت فایده قابل توجهی داشته باشه.

**Comment by saadat99** [comment]
سلام. من از کاربران گوگل داکز هستم. این برنامه یک فونت درست حسابی فارسی نداره.
وقتی اینهمه فونت فارسی آزاد هست چرا نباید پیگیری کنیم. مشکل چیه؟
درضمن من از گوگل فونتز توی طراحی وبسایت هم استفاده میکنم.

**Comment by behdad** [comment]
https://twitter.com/behdadesfahbod/status/1295149645253902336

**Comment by zoghal** [comment]
> 
> 
> https://twitter.com/behdadesfahbod/status/1295149645253902336
جناب اسفهبد خواستم از بابت این حرکت‌تون شخصا ازتون تشکر کنم.
درضمن امیدوارم امین عابدی عزیز را هم فراموش نفرمایید، کارهاشون حرف نداره: https://github.com/aminabedi68/
ممنون

**Comment by behdad** [comment]
@zoghal Want to share a screenshot of the your DM blackmail message to me on Twitter calling me "fake Steve Jobs" and demanding that I pay you $10,000 or something within a 24-hour timeframe or you'll expose me? Or you want me to go dig my screenshot of that message-request?

**Comment by zoghal** [comment]
با پوزش فروان از راستی‌کردار عزیز، که مجبورم آف تاپیک بزنم.

جناب @behdad:
به روزگاری که عده‌ای دلسوزانه در حال تلاش برای تغییر «شرایط موجود» بودند، عده‌ای دیگر سودجویانه مشغول استفاده از «شرایط موجود» شدند. کسانی که آرزوها و آرمان‌های مردمی رنج‌کشیده را به باد فنا می‌دهند و حتی گستاخانه به آنان فخر هم می‌فروشند. آنانی که مصیبت‌ها و بحران‌های اجتماعی را به چشم فرصتی منفعت‌طلبانه می‌نگرند و آینده جامعه‌ای را به گرداب تباهی خویش می‌کشند. آنان که دیروز و امروز و آینده ایران را ویران کرده‌اند. **و اینچنین است که تا هنگام مقابله عمومی با این عده، هیچ تغییر و بهبودی حاصل نمی‌شود و هر روزمان بدتر از دیروزمان است.**

بازهم اشتباه کردید! ببنید بنده به این دلیل ازتون تشکر کردم، چون بالاخره از نزدیک مشاهده کردم که دقیقا یکی از همان سودجویان زمانه‌‌ام، سرانجام به خودش آمده و داره یک کار درست و پسندیده می‌کند. از نظر من این کار شما بسیار لایق تقدیر و تشکر است. لذا بدون هرگونه تعارف و توجیهی یا...  بنده بازهم به نوبه خودم از بابت این اقدام خوب و پسندیده‌‌ای که انجام دادید تشکر می‌کنم، علتش هم ساده است، بنده «منافع شخصی» را مستقل از «منافع جمعی» می‌دانم و از هر کار خوب که برای جامعه‌ام انجام شود در حد توانم و تا آنجایی که برایم مقدور باشد از این کارها حمایت و پشتیبانی می‌کنم.



> Want to share a screenshot of the your DM blackmail message to me on Twitter calling me "fake Steve Jobs" and demanding that I pay you $10,000 or something within a 24-hour timeframe or you'll expose me??

دقیقا نمی‌دانم از چه موضوعی دارید صحبت می‌کنید، راستش خیلی وقته که شما را پیگیری‌ نمی‌کنم. اما در مورد اسکرین‌شات گرفتن لازم است این نکات را به عرض شما برسانم:

۱- بنده معتقدم راه راستی از دروغ نمی‌گذرد و واقعیت آزاردهنده به از دروغ آرامش‌دهنده است.
۲- از طرف دیگر معتقدم حق و وظیفه یک محقق ایجاب می‌کند، که برای دستیابی به واقعیت‌ها و بیان آنها بکوشد. این حق و وظیفه را نمی‌توان نادیده گرفت یا پایمال کرد. اگر کار محقق موجب آزردگی و اضرار عده‌ای می‌شود، می‌باید این مشکل و راه‌حل آنرا در جای دیگری جستجو کند. برای چنین جستجو و بررسی، باز هم به وجود یک محقق واقعگرا نیاز است.

بنده این مشکل را با اسکرین‌شات حل کردم و حقیقت رو هم بیان کرده و می‌کنم. حالا شما یا هر شخص دیگری احیانا فکر می‌کند که من مستنداتم رو بصورت فیک ایجاد می‌کنم.پایه باشید و در یک استوری آنلاین بیایید این ادعای خودتان را اثبات کند. چون بنده برعکس شما وقتی قول می‌دم سر حرفم می‌مانم، لذا اگر بتوانید یک مورد را اثبات کنید من بصورت تصویری از همه عذرخواهی کنم.🤨


>  Or you want me to go dig my screenshot of that message-request

جناب! ایا منظورتان همان پیامی است که نوشته بودم «تا ساعت ۱۲ شب ۲۸ اردیبهشت فرصت پاسخگویی دارید در صورت تمایل([همراه با این ویدیو؟!](youtu.be/9sqXenjAwsA))😁. داداش اگر اینو میگی که حله! آخه این احترام من بود واسه شخصی که فکر می‌کردم مرده و حداقل یکمی از مرادنگی باید بویی برده باشه! در حقیقت یک لطف به شما بود تا فرصت لازم را داشته باشید برای پاسخ‌گویی رفتارتان و دفاع از خودتان. می‌پذیریم که اشتباه می‌کردم و از بابتش هم پشیمانم! 

درکل از نظر بنده هیچ مشکلی نداره! خواستید منتشرش کنید. شما که جدیدا توی مدیوم دست به قلمتان خوب شده و داستان مینویسید. خوب در مورد این هم بنویسید و شفاف‌سازی کنید که داستان چی بوده. به هر حال از دو حالت خارج نیست یا مثل [[...](https://peertube.social/video-channels/flossir/videos)] فرافکنی می‌کنید، که خیلی دمتون گرم یا خوب حقیقت را بیان می‌کنید. پس بسم‌الله! ما اهل غایم موشک بازی و آهسته بیا ایران و برو نیستیم، درضمن مسولیت کارهای خوب و بدمان را هم برعهده می‌گیریم. پس باکی نیست😎.


در پایان مجدد از صابر عزیزم عذرخواهی می‌کنم، چون میدونم از این حرف‌ها بدش میاد، اما خوب چاره‌ای نبود.
امیدوارم جناب اسفهبد اینجا رو با توییتر اشتباه نگیرند و هر حرفی داشتند آنجا من در خدمتشان حاضرم.
پایان

**Comment by Nothehi** [comment]
یکی میشه وضعیت این issue رو مشخص کنه!! قصد اضافه کردن دارید یا نه؟ تلاشی صورت گرفته اصلا ؟! ما هنوز منتظریم از این فونت داخل گوگل فونت استفاده کنیم!

**Comment by venusbahar** [comment]
> سلام. من از کاربران گوگل داکز هستم. این برنامه یک فونت درست حسابی فارسی نداره.
> وقتی اینهمه فونت فارسی آزاد هست چرا نباید پیگیری کنیم. مشکل چیه؟
> درضمن من از گوگل فونتز توی طراحی وبسایت هم استفاده میکنم.

سلام، من هم از کاربران سرویس‌های نوشتاری گوگل مثل داک، شیت، داک، فرم و ... هستم. لطفاً فونت وزیر را به گوگل فونت اضافه کنید تا ما کاربران فارسی زبان بتونیم راحت‌تر با سرویس‌های آنلاین گوگل کار کنیم.
در صورت پیگیری، حتی ممکنه گوگل از فونت وزیر به عنوان فونت فارسی و عربی در تمامی سرویس‌هایش استفاده کنه

**Comment by zoghal** [comment]
خدمت دوستان عرض کنم، تا آنجایی که من پیگیری کردم پروسه اضافه شدن فونت وزیر آغاز شده و تو فهرست اضافه شدن قرار گرفته([اینجا](https://github.com/google/fonts/projects/7#card-47508965))

اما یک نکته‌ای وجود داره اینه که حتی اگر این فونت به گوگل فونت اضافه بشه، ممکنه قابل استفاده در گوگل داکز نباشه، کماکان که شاهدیم خیلی از فونت‌های خود گوگل هم قابل استفاده نیست :)

در آخر پیشنهاد می‌کنم بجای این ایشو! ایشوهای زیر را پیگیری کنید تا کار سریع‌تر انجام بشه:
https://github.com/google/fonts/issues/2622
https://github.com/google/fonts/issues/2975

**Comment by hosseinshirmardi** [comment]
سلام. شاید جای مناسبی برای این نباشه، ولی چون دوستان مطرح کردند، این ترفند فعلی هست که بنده برای استفاده از قلم پارسی در Google Docs استفاده می‌کنم.
https://virgool.io/@hossein_shirmardi/google-docs-persian-font-change-obmwnxprhk9e

امیدوارم زودتر قلم وزیر و سایر قلم‌های آزاد روی Google Fonts قرار بگیرند.
@Pro-Ton @zoghal @venusbahar @saadat99  @ghaznavipc

**Comment by AlirezaIvaz** [comment]
دوستان عزیز سلام.
فونت وزیر امروز به [اهداف سه‌ماهه ۲۰۲۲ گوگل فونت](https://github.com/google/fonts/milestone/19) اضافه شده و احتمالا تا آخر بهار اضافه می‌شه.
البته [اینجا](https://github.com/google/fonts/issues/2975#issuecomment-1016947844) گفتن که نمی‌شه همون جوری که هست به گوگل فونت اضافه بشه چون بخش‌های دژاوو، OFL نیستن و باید حذف بشن (که البته من نمی‌دونم دقیقا شامل کدوم بخش‌های فونت می‌شه).

**Comment by AlirezaIvaz** [comment]
دوستان عزیز سلام.
بالاخره فونت وزیر به اهداف سه‌ماهه گوگل فونت ([اینجا](https://github.com/google/fonts/milestone/19)) اضافه شد و احتمالا تا آخر بهار می‌بینیمش :)
البته [اینجا](https://github.com/google/fonts/issues/2975#issuecomment-1016947844) جناب کراسلند گفتن که بخش‌های دژاوو فونت رو چون OFL نیستن حذف می‌کنن.

**Comment by rastikerdar** [comment]
فونت وزیر مشکلی نداره. البته اونها حق دارند سخت‌گیری کنند. من خودم این رو می‌پسندم. نسخه اول وزیر از روی فونت دژاوو شروع شد چون اون موقع من نیاز به یک بستر داشتم. اون بخشی که من از فونت دژاوو استفاده کردم در مالکیت عمومی بود. الان دیگه هیچ ارتباطی بین تایپ‌فیس وزیر و دژاوو نیست و همه از نو ساخته شده‌اند. تنها چیزی که مونده اینه که یه سری جدول داده در مورد حروف است که در تمام فونت‌ها مشترکه. مثل جدول توی عکس. اون نسخه کوچک اولیه از دژاوو هستهٔ شروع بود که به تدریج بزرگ‌تر و گسترده تر شد و بسیاری جدول دیگه هم مثل کرنینگ‌ها بهش اضافه شد. نمی‌دونم من باید با اون رکوردهای اولیه چه کار کنم! مثلا دوباره از اول دستی خودم عینا همین‌ها رو بنویسم چراکه در همه فونت‌ها یکی هست و نمی‌دونم اصلا چیزی که در همه جا یکی هست شامل لایسنس میشه یا نه! تازه خود دژاوو گفته در مالکیت عمومیه! مثلا توی این جدول می‌گه نویسه انتهایی هر حرف کدام گلیف تعریف شده.
![Screenshot at 2022-01-20 14-48-24](https://user-images.githubusercontent.com/3116038/150329995-e101be3b-a8ae-4a10-8d68-52c167e478ad.png)

به هر حال نسخه جدید وزیر قراره با نام جدید منتشر بشه و من توی اون نسخه این‌ها رو همه مفصلا توضیح می‌دم که شفاف‌سازی بشه که وزیر هیچ مشکلی از بابت لایسنس نداره. به اون ایشو هم بعدا پاسخ میدم که مشکلی پیش نیاد.

**Comment by ghaznavipc** [comment]
> سلام. شاید جای مناسبی برای این نباشه، ولی چون دوستان مطرح کردند، این ترفند فعلی هست که بنده برای استفاده از قلم پارسی در Google Docs استفاده می‌کنم. https://virgool.io/@hossein_shirmardi/google-docs-persian-font-change-obmwnxprhk9e

سلام. ترفندتون جالبه. ولی با این حال این ترفند بیشتر شبیه گول‌زدن چشمان خودمونه تا تغییر واقعیِ فونت مقصد؛ اگه شخص دومی با کامپیوتر خودش بیاد داخل سند، اون رو با فونت سیستم‌عاملش میبینه. احتمالا فکر کنم اگه pdf هم خروجی بگیرم، خروجیش رو توی سیستم خودم هم با فونت سیستم‌عامل نشون بده... با این حال ممنون بابت پیشنهاد. هرچی هم باشه از هیچی که خیلی بهتره 👍 خیلی ممنون

**Comment by ghaznavipc** [comment]
> دوستان عزیز سلام. فونت وزیر امروز به [اهداف سه‌ماهه ۲۰۲۲ گوگل فونت](https://github.com/google/fonts/milestone/19) اضافه شده و احتمالا تا آخر بهار اضافه می‌شه.

ایول! بالاخره! بالاخره!!! خدا رو شکر!

**Comment by ghaznavipc** [comment]
> فونت وزیر مشکلی نداره. البته اونها حق دارند سخت‌گیری کنند. من خودم این رو می‌پسندم. نسخه اول وزیر از روی فونت دژاوو شروع شد چون اون موقع من نیاز به یک بستر داشتم. اون بخشی که من از فونت دژاوو استفاده کردم در مالکیت عمومی بود. الان دیگه هیچ ارتباطی بین تایپ‌فیس وزیر و دژاوو نیست و همه از نو ساخته شده‌اند. تنها چیزی که مونده اینه که یه سری جدول داده در مورد حروف است که در تمام فونت‌ها مشترکه. مثل جدول توی عکس. اون نسخه کوچک اولیه از دژاوو هستهٔ شروع بود که به تدریج بزرگ‌تر و گسترده تر شد و بسیاری جدول دیگه هم مثل کرنینگ‌ها بهش اضافه شد. نمی‌دونم من باید با اون رکوردهای اولیه چه کار کنم! مثلا دوباره از اول دستی خودم عینا همین‌ها رو بنویسم چراکه در همه فونت‌ها یکی هست و نمی‌دونم اصلا چیزی که در همه جا یکی هست شامل لایسنس میشه یا نه! تازه خود دژاوو گفته در مالکیت عمومیه! مثلا توی این جدول می‌گه نویسه انتهایی هر حرف کدام گلیف تعریف شده. ![Screenshot at 2022-01-20 14-48-24](https://user-images.githubusercontent.com/3116038/150329995-e101be3b-a8ae-4a10-8d68-52c167e478ad.png)
> 
> به هر حال نسخه جدید وزیر قراره با نام جدید منتشر بشه و من توی اون نسخه این‌ها رو همه مفصلا توضیح می‌دم که شفاف‌سازی بشه که وزیر هیچ مشکلی از بابت لایسنس نداره. به اون ایشو هم بعدا پاسخ میدم که مشکلی پیش نیاد.

آقا من رفتم در حد دانشم همین پیام رو به انگلیسی ترجمه و توی اون ایشو قرار دادم. امیدوارم حلال کنید و امیدوارم بد نباشه این حرکتم. اگه کارم اشتباه بوده بفرمایید تا اصلاح یا پاکش کنم.

**Comment by zoghal** [comment]
> به هر حال نسخه جدید وزیر قراره با نام جدید منتشر بشه و من توی اون نسخه این‌ها رو همه مفصلا توضیح می‌دم که شفاف‌سازی بشه که وزیر هیچ مشکلی از بابت لایسنس نداره. به اون ایشو هم بعدا پاسخ میدم که مشکلی پیش نیاد.

صابر جان توی لایسنس ذکر کردی:

> "The first version of Vazir was based on DejaVu 2.35 (was committed to the public domain) to begin designing and developing this new typeface."

کلا حذفشون کن و محتوای لایسنس ofl رو بزار

**Comment by rastikerdar** [comment]
@ghaznavipc
ممنون. البته من می‌خواستم اول خودمون به جمع‌بندی و راه‌حل برسیم و بعد اونجا صحبت کنم ولی خب فکرش که می‌کنم اتفاقا این هم بد نیست که شما گفتید که ما شفاف هستیم.

@zoghal
صالح توی قسمت لایسنس فونت گفته شده که لایسنس او‌اف‌ال هست و حتی آدرسش هم قرار داده شده. این توی قسمت توضیح بود و من اصرار دارم که به دژاوو اشاره کنم چون کمک کرد برای شروع پروژه. حالا در ادامه همین عبارت خواهم نوشت که تمام گلیف‌ها عوض شده‌اند. البته من نمی‌دونم چرا وقتی که خودشون گفته‌اند مالکیت عمومیه باز این همه سرش بحث میشه! خود من هم که مجوز رو از مالیکت‌عمومی تغییر دادم برای این بود که افراد مختلف برای استفاده از فونت اجازه می‌گرفتند یا در مورد لایسنس توضیح می‌خواستند من هم به نظرم اومد که یک چیز رایج بگذارم.


راستی دوستان اگر در مورد این ایشو هم نظری داشتید بگید: https://github.com/rastikerdar/vazir-font/issues/230

**Comment by zoghal** [comment]
> @zoghal صالح توی قسمت لایسنس فونت گفته شده که لایسنس او‌اف‌ال هست و حتی آدرسش هم قرار داده شده. این توی قسمت توضیح بود و من اصرار دارم که به دژاوو اشاره کنم چون کمک کرد برای شروع پروژه. حالا در ادامه همین عبارت خواهم نوشت که تمام گلیف‌ها عوض شده‌اند. البته من نمی‌دونم چرا وقتی که خودشون گفته‌اند مالکیت عمومیه باز این همه سرش بحث میشه! خود من هم که مجوز رو از مالیکت‌عمومی تغییر دادم برای این بود که افراد مختلف برای استفاده از فونت اجازه می‌گرفتند یا در مورد لایسنس توضیح می‌خواستند من هم به نظرم اومد که یک چیز رایج بگذارم.

صابر جان این که چرا اینقدر به این موضوع هستند رو نمی‌دونم، اما بنظرم این پافشاری شما فعلا دارد به ضرر جامعه مصرف کننده تمام می‌شود. من اگر جای شما بودم برای اینکه فونت زودتر در سرویس گوگل بره تا بتونه مشکلاتی که فارسی زبان‌ها در سرویس‌های گوگل داکز دارند حل بشه! حتما بیخیال این پافشاری می‌شدم :)

**Comment by ghaznavipc** [comment]
> صابر جان این که چرا اینقدر به این موضوع هستند رو نمی‌دونم، اما بنظرم این **پافشاری** شما فعلا دارد به ضرر جامعه مصرف کننده تمام می‌شود. من اگر جای شما بودم برای اینکه فونت زودتر در سرویس گوگل بره تا بتونه مشکلاتی که فارسی زبان‌ها در سرویس‌های گوگل داکز دارند حل بشه! حتما بیخیال این **پافشاری** می‌شدم :)

ایشون هیچ پافشاری‌ای نکردن. متوجه نمیشم این شفاف‌سازی و پاسخِ ایشون کجاش پافشاری محسوب میشه. فرمود که از بابت کپی‌رایت هیچ‌گونه مشکلی نداره چون لایسنس قسمتی که استفاده کرد PD بود و حتی با این وجود همشون عوض شدن و چیزی از اون قسمتی که گرفته بودن وجو نداره. و حتی با این وجود که مشکلی نداره و همشون تغییر کردن، بازم قراره در آینده یه فونت ۱۰۰ درصد _بی‌حاشیه_ و کاملا شفاف از هر جهت بسازه. لطفا دیگه مودبانه یا غیرمودبانه نظرات سمی نفرستید (مثل قبلی که بالای ۵۰ تا دیس‌لایک گرفتید).
تمام کاری که ایشون داره انجام میده همکاریه و لا غیر!

**Comment by ghaznavipc** [comment]
> صابر جان این که چرا اینقدر به این موضوع هستند رو نمی‌دونم، اما بنظرم این **پافشاری** شما فعلا دارد به ضرر جامعه مصرف کننده تمام می‌شود. من اگر جای شما بودم برای اینکه فونت زودتر در سرویس گوگل بره تا بتونه مشکلاتی که فارسی زبان‌ها در سرویس‌های گوگل داکز دارند حل بشه! حتما بیخیال این **پافشاری** می‌شدم :)

ایشون هیچ پافشاری‌ای نکردن. متوجه نمیشم این شفاف‌سازی و پاسخِ ایشون کجاش پافشاری محسوب میشه. فرمود که از بابت کپی‌رایت هیچ‌گونه مشکلی نداره چون لایسنس قسمتی که استفاده کرد PD بود و حتی با این وجود همشون عوض شدن و چیزی از اون قسمتی که گرفته بودن باقی نمونده. و حتی با این وجود که مشکلی نداره و همشون تغییر کردن، بازم قراره در آینده یه فونت ۱۰۰ درصد _بی‌حاشیه_ و کاملا شفاف از هر جهت بسازه. لطفا دیگه مودبانه یا غیرمودبانه نظرات سمی نفرستید (مثل قبلی که بالای ۵۰ تا دیس‌لایک گرفتید).
تمام کاری که ایشون داره انجام میده همکاریه و لا غیر!

**Comment by ghaznavipc** [comment]
البته خیلی خوبه که به فکر جامعه‌ی ایرانی و زودتر قرار گرفتن این فونت درون گوگل‌داکز هستید. ازین بابت ازتون سپاسگزارم.

**Comment by rastikerdar** [comment]
خب مراحل این موضوع انجام شد #231 و بقیه به خود گوگل‌فونتز مربوط میشه. با تشکر از مشارکت دوستان

**Comment by mirismaili** [comment]
![image](https://user-images.githubusercontent.com/15800189/161388736-f446c328-6c6a-4396-8ed6-cc72a63f7bb8.png)
