### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by sajaddp** [rastikerdar/vazirmatn#61]
سلام
اینکه مدتی قبل نسخه bower و npm
فونت رو منتشر کردید خیلی خوب شد، ممنونم میشم اگر لطف کنید بر روی packagist.org
هم قرار بدید تا بتونیم از طریق کامپوزر هم دریافتش کنیم.

تشکر

**Comment by rastikerdar** [comment]
سلام
بهتره این موضوع از طریق دوستان بیرون از خود مخزن مثل مواردی که در صفحه مرابخوان آمده انجام بشه. خود مخزن تنها روش ان‌پی‌ام که رایجترین روش است رو ارائه می‌کنه. ممنونم برای این ایشو.
