### ISSUE TITLE
مشکل نمایش فونت در سیستم رنگ rgba

### ISSUE THREAD

**Issue by SadeghPM** [rastikerdar/vazirmatn#72]
با سلام و تشکر از زحماتتون
در آخرین ورژن وزیر یعنی ۱۳.۰.۱ در نمایش فونت با یک رنگ
rgba(0,0,0,0.54)
این رو دیدم:
![vazir_font_display_problem](https://user-images.githubusercontent.com/9298600/28996001-81cb6fc4-7a0c-11e7-8b81-ef36fe30b0fc.png)
 میبینین که **خط اول** یه **سری نقاط** وجود دارند در فونت که رنگش با بقیه **متفاوت** هست.
برای تست میتونین این رنگ رو به یه متن تو مرورگر بدین:
rgba(0,0,0,0.54)
به نظر نقاط اتصال حروف به هم یه نقطه رنگی میگیره. البته نمیدونم ایراد از فونت هست یا از چیزی دیگه.

**Comment by SadeghPM** [comment]
البته فونت ایران سنس هم همینطور میشه:
![iransans_](https://user-images.githubusercontent.com/9298600/28996094-181c9dc6-7a0e-11e7-81cf-adb818ac3e08.png)

**Comment by Javid-Izadfar** [comment]
<p dir="rtl">صادق‌جان سلام</p>
<p dir="rtl">این موردی که شما بهش اشاره کردی، مسئله‌ی تازه‌ای نیست و خیلی از فونت‌های فارسی این مشکل رو دارن.</p>
<p dir="rtl">این مشکل به این دلیل پیش میاد که برای چسبیدگی حروف به هم بعضی از حروف داخل هم میرن. شاید این برگرده به بی دقتی طراح، شاید هم از لحاظ فنی پیاده‌سازیش آسون نباشه.</p>
<p dir="rtl">توی تجربه‌ی شخصی خودم، فقط فونت بهداد از جناب سوزنچی بودن که این حالت رو نداشت.</p>

<p dir="rtl">ولی راه حل برای من و شمای کاربر؟</p>
<ol dir="rtl">
   <li>به جای <code dir="ltr">rgba</code>، از <code dir="ltr">opacity</code> استفاده کن. (شاید به یک <code dir="ltr">span</code> داخل پاراگرافت احتیاج پیدا کنی)</li>
   <li>مقدار <code dir="ltr">letter-spacing</code> رو افزایش بده</li>
</ol>

**Comment by SadeghPM** [comment]
<div dir="rtl">
ممنون جاوید جان
<div dir="rtl">
 من از angular material استفاده میکنم که یکم سخت هست در سیستم کلی رنگ تغییر ایجاد کنم
</div>

**Comment by SadeghPM** [comment]
جناب راستیکردار امکان تصحیح این مورد هست؟

**Comment by rastikerdar** [comment]
با سلام و احترام
خب این موردی که فرمودید در واقع یک اشکال هست.
حقیقتش در نسخه های اولیه، این ناحیه همپوشانی ناچیز بود و شاید به سختی دیده می‌شد اما مشکل این بود که در همان زمان گزارش‌هایی می‌رسید (اندروید و اپل) مبنی بر فاصله افتادن بین حروف متصل. خود من هم به کرات این مشکل رو در مرورگر اندروید می‌دیدم. تنها راه حل همین افزایش ناحیه همپوشانی بود. تا الان راه حلی براش پیدا نکردم.

**Comment by zoghal** [comment]
> توی تجربه‌ی شخصی خودم، فقط فونت بهداد از جناب سوزنچی بودن که این حالت رو نداشت.

خوشحالم این رو می‌شونم، ولی بعید می‌دونم این مشکل در بهداد وجود نداشته باشد، ۱۰۰٪ داره اما نسبت به سایر فونت‌ها زیاد خودش رو نشون نمیده. علتش هم این هست که ناحیه همپوشانی و سایر مباحث مرتبط با متریک گلیف‌ها توسط RFB دقیقا در هر بازسازی محاسبه میشوند و البته من کمی متفاوت با سایرین در پیاده‌سازی عمل می‌کنم.

# بریم تو فار زکات علم:

## ریشه این مشکل:

۱- پیشنهاد ناحیه همپوشانی از طرف ماکروسافت ارائه شده([ببینید](https://www.microsoft.com/typography/cursivescriptguidelines.mspx)) و از اینجا این مورد تبدیل شد به یک استاندارد نانوشته شده در تایپ فارسی. نکته جالب اینه که پیشنهاد شده در سمتی که گلیف با گلیف بعدی ارتباط برقرار می‌کند این ناحیه در نظر گرفته شود. نه هر دو طرف!!!

۲- در دو دهه گذشته ناهماهنگی بین OpenType Layout system ها باعث سردرگرمی میشه، توسعه‌دهندگان فونت قدیمی میان در هر طرفی که وصل میشه رو ناحیه همپوشانی در نظر می‌گیرند. در بعضی از فونت‌های قدیمی مشاهده کنم که این ناحیه غیر عادی و طویل تعریف شدهکه احتمالا برای استفاده از خصوصیت کم و زیاد کردن فواصل حروف باشد.

۳- اکثر کسانی که ظاهرا یا واقعا در حال توسعه‌ فونت فارسی هستند با افسوس فراوان بدون داشتن اطلاع کافی و دقیق از مباحث پایه و آکادمیک فنی پیاده‌سازی فونت، و بدون کمی صرف وقت جهت بروز رسانی خود به صورت آزمون خطا و الگو برداری از یک فونت شناخته شده و مطرح دیگر فونت‌های خود رو توسعه می‌دهند. (به استثنای اوپن سورسی‌ها). و همواره وقتی علت را سوال می‌کنی منبع حرفشان یک فونت هست.

۴- علت بعدی این هست که طیف مصرف کننده‌ها فراوان است و انجام تست‌های لازم برای کشف مشکلات و دلایل آن بسیار سخت، زمانبر و دردسرهای فراوانی دارد باعث شده که کمی در اینگونه مشکلات تنبلی کنیم، بهانه بتراشیم و مشکل را بندازیم گردن تکنولوژی و .... 

۴- متاسفانه اهل گزارش کردن مشکلات هم نیستیم.

-----

## این تست‌های من روی ویندوز ۱۰ بروز شده با تمامی مرورگر ها

# IE:

![ie](https://user-images.githubusercontent.com/174688/29292118-2ca6747a-815b-11e7-9fc5-6ba40dd4ead5.gif)


# Edge:

![edge](https://user-images.githubusercontent.com/174688/29292131-38c54510-815b-11e7-9a11-f6711fff25ba.gif)


# FireFox:
![firefox](https://user-images.githubusercontent.com/174688/29292078-04f78932-815b-11e7-8937-8a34ac928eb1.gif)


# Chrome Canary:
![chorome](https://user-images.githubusercontent.com/174688/29292124-34980144-815b-11e7-9dc8-3fb5b20133fe.gif)
پ.ن: شدیدا برای گوگل متاسفم که در تیم توسعه فونت و نمایش متن خود شخصی را در اختیار دارد که مدعی شدند که ۱۵ سال است که روی خط فارسی کار می‌کند، دارد 👎 


------------------

# راهکاری برای بهبود بخشیدن این مشکل:

1- متاسفانه این مشکل در ابتدا باید توسط موتور‌های نمایش متن هندل شوند. اما میشود مشکل رو کمی بهبود بخشید و تا کمتر جلوه نمایی کند، تو تست‌هایی متعددی که انجام دادم روش زیر بهترین حالت بود مخصوصا در سایز ریز این مشکل کمتر به چشم مخاطب درگیر می‌شود. این فرمولی هست که من استفاده می‌کنم:

![screenshot 2017-08-15 04 11 05](https://user-images.githubusercontent.com/174688/29296937-aa76bc9a-8172-11e7-93bd-131c2e7a2897.png)

۱- مقدار ضخامت اصلی را بدست آورید
۲- دایره‌ای با قطر مقدار ضخامت اصلی ایجاد و از وسط نصف کنید. شیپ حاصل را فقط در سمت چپ حروفی که چپ وصل هستند قرار بدید.
۳- مقدار lsb یا Left Side Bearing می‌بایست حتما با مقدار عرض نیم دایره یکسان باشد. در تصویر منفی ۸۵ هست. در حروف راست وصل RSB را صفر قرار بدید.
۴- هنگام گرفتن خروجی نهایی حتما باید کل گلیف یک شیپ فلت شده باشند، یعنی overlaps نداشته باشند.(هنگام استفاده از کامپوننت شیپ یا رفرنس شیپ دقت شود)
۵- سایر حروف مفرد مثل ا، ر ، ل ، ن مقدار LSB و RSB آنها باید + ۸۵ باشد.


این دستور عمل رو انجام بدید بعدش متوجه خواهید شد نصف کرنینگ‌هاتون اضافه هستند.
 کرنینگ کمتر، حجم پایین تر

صابر جان هر وقت امتحانش کردی نظرت رو باهام در میون بزار 
شاد و پیروز باشید

**Comment by aminabedi68** [comment]
سلام، توضیحات صالح خیلی خوب و جامع بودن، البته یه راه موقت برای رفع این مشکل اینه که همیشه از شفافیت ۱۰۰ درصد استفاده کنیم و یا از فایل وکتور شده و یکپارچه متن استفاده کنیم، ولی به هر حال این مشکل باید رفع بشه، من حتما با روشی که صالح گفت این مورد رو برای بروزرسانی بعدی فونت استعداد در نظر میگیرم، ممنون از همگی

**Comment by rastikerdar** [comment]
این مشکل در نسخه‌های جدید این فونت کمتر شده اما خب کار زیادی از دست طراح برنمیاد. با تشکر از مشارکت دوستان
