### ISSUE TITLE
مشکل در حروف ر ز ژ

### ISSUE THREAD

**Issue by rasa-app** [rastikerdar/vazirmatn#82]
با سلام و با تشکر از فونت زیبای شما من از این فونت در گزارش ساز 
Jasper Reports
استفاده می کنم اما حروف ر ز ژ در برنامه و در هنگام چاپ به شکلی که در عکس ضمیمه مشاهده می کنید
 نمایش داده می شود ولی هنگامی که از فونت های دیگر مانند 
BNazanin
استفاده می کنم همه چیز درست است
با تشکر
![capture](https://user-images.githubusercontent.com/32872864/34637960-db9b5148-f2d6-11e7-918c-20513202bd80.PNG)

**Comment by rastikerdar** [comment]
با سلام و احترام
مشخصا به دلیل کرنینگی هست که روی این سه حرف انجام شده و ماژول چاپگر اون رو به درستی تفسیر نمی‌کنه. اگر اشتباه نکنم در فونت های بی نازنین و امثالهم کرنینگی انجام نشده.
نمی‌دونم شاید توی ایده «فونت سرویس» نسخه بدون کرنینگ هم بد نباشه اضافه بشه!
[github.com/rastikerdar/fontservice](https://github.com/rastikerdar/fontservice)

**Comment by rasa-app** [comment]
با تشکر از توضیحات شما

**Comment by rastikerdar** [comment]
فکر می‌کنم با نسخه اخیر وزیر این مشکل حل شده باشه.
[rastikerdar.github.io/vazir-font](https://rastikerdar.github.io/vazir-font/)

**Comment by rasa-app** [comment]
با سلام و تشکر

این مشکلی که زحمت کشیدید و حل کردید مجددا در وژن 29.0.0 ایجاد شده

![Screenshot 2021-06-15 122620](https://user-images.githubusercontent.com/32872864/122017076-e397bd80-cdd6-11eb-8466-b5a641836cf2.jpg)

**Comment by rastikerdar** [comment]
سلام
راستش من از تضویر اینطور به نظرم میاد که این نسخه قدیمی است. مطمئنید نرم‌افزار داره از نسخه آخر استفاده می‌کنه؟

**Comment by rastikerdar** [comment]
من دوباره دقت کردم دیدم مشکل «ع» هنوز توی نسخه آخر برطرف نشده. فقط یک سوال دارم اینکه حروف بعد از روز «حداکثر تا پانزده روز...» توی متن تصویر چیه تا مشکلش رو پیدا کنم؟ ممنون

**Comment by rasa-app** [comment]
تشکر از پاسخگویی شما
ورژن فونت 29 است ولی عکسی که من گرفتم از خروجی پی دی اف است شاید بخاطر این درست دیده نمیشه
متن عکس:
 ...حداکثر تا پانزده روز پس از تاریخ این ابلاغ کارمند

**Comment by rastikerdar** [comment]
من توی نسخه جدید، ایراد «ع غ» رو برطرف کردم اما هر چه گشتم علت مشکل «پس» رو توی تصویر شما پیدا نکردم و نمی‌دونم به «ع غ» ربطی داشته یا نه. شاید الان مشکلش رفع شده باشه.  
https://github.com/rastikerdar/vazir-font/releases/tag/v29.0.2

اگر همچنان ایراد داشت ممنون می‌شم دقیقا خود متن رو هم اینجا کپی بفرمایید.

**Comment by rastikerdar** [comment]
امیدوارم این مشکل در نسخه ۳۲ یعنی وزیرمتن حل شده باشه.
