### ISSUE TITLE
فایل less و sass

### ISSUE THREAD

**Issue by TheYahya** [rastikerdar/vazirmatn#88]
<p dir="rtl">
سلام
</p> 
<p dir="rtl">
میشه فایل‌های <kbd>less</kbd> و <kbd>sass</kbd> رو در خروجی(dist)  و فایل <kbd>.zip</kbd> اضافه کنیم تا در هر پروژه بشه براحتی بعنوان ی ماژول به فایل‌هامون ایمپورت کنیم.
 </p>

**Comment by rastikerdar** [comment]
سلام
شما چه نوع ویژگی یا کدی برای این نوع فایل‌ها مد نظرتون هست؟

**Comment by SadeghPM** [comment]
به راحتی با ایمپورت فایل css میشه تو scss از فونت استفاده کرد.

**Comment by TheYahya** [comment]
<p dir=rtl">
هدف من ساده سازی روند نصب و پیاده‌سازیه، اینجوری که فقط مسیر دایرکتوری فونت رو ست کنی و css همه‌ی نسخه‌هاش جنریت بشه.
</p>
<p dir=rtl">
ایده‌ام بست دادنه این پول‌ریکوئسته 
</p>
https://github.com/rastikerdar/vazir-font/pull/60

**Comment by rastikerdar** [comment]
راستش من متوجه منظور شما و #60 نشدم. ببخشید یعنی نمی‌دونم طبق فرمایش آقا صادق مشکل فایل سی‌اس‌اس فعلی برای ایمپورت کردن توی لس یا ساس چیه و روش پیشنهادی شما چگونه و دارای چه مزیتی هست.

**Comment by SadeghPM** [comment]
در یک فایل scss:
```scss
@import "~vazir-font/dist/font-face";
@import "~font-awesome/scss/font-awesome";
$body-font-family: Vazir, Helvetica, Roboto, Arial, sans-serif;
```
همان طور که مثلا ‍
`fontawsome` 
.استفاده میشه ، وزیر هم استفاده میشه
من هم مثل جناب راستی‌کردار متوجه مشکلتون نمی‌شم.

**Comment by TheYahya** [comment]
درسته، ولی واسه نسخه‌های "اعداد فارسی" و ... نداریم چیزی و باید دستی مسیرشون رو ست کرد.

**Comment by mokhosh** [comment]
اتفاقا استفاده از لس و سس برای رفع این مشکل خیلی خوبه
کافیه یه میکس-این اضافه بشه و قبل از ایمپورت کردن فایل توی یه متغیر مشخص کنیم کدوم نسخه از فونت رو میخایم

در حال حاضر خیلی تغییر دادن فونت به نسخه اعداد فارسی مشقت اضافه داره

**Comment by rastikerdar** [comment]
برخی دوستان درخواست کرده بودند که برای هر کدام از حالت‌های مختلف مثل «تمام ارقام فارسی» هم فایل سی‌اس‌اس بزاریم. راهی که فکر می‌کنم پیشنهاد شد این بود که توی پوشه هر کدوم یه دونه فونت‌فیس.سی‌اس‌اس بزاریم. چون همه شاید نخوان برای هر پروه‌ای از لس یا سس استفاده کنن.
```
dist/
    fontface.css
    Farsi-Digits/
        fontface.css
        ...
    Without-Latin/
        fontface.css
        ...
    ...
```

البته نمی‌دونم نامگذاری‌ها به چه صورت باشه.مثلا:
`fontface-fd.css`
یا همون
‍`fontface.css`

یا اینکه درون سی‌اس‌اس
`font-family: Vazir-FD;`
باشه یا همون
‍‍‍`font-family: Vazir;`
باشه.

برای سس هم دوستان هر طور صلاح می‌دونن. اگر این موضوع به سرانجام برسه فکر می‌کنم بهتر بشه یه فایل سس مناسب هم پیاده کرد.

**Comment by mahdi-alavi** [comment]
<p dir="rtl">
بهترین نمونه ‍‍‍‍<kbd>mixin</kbd> برای <kbd>SASS</kbd> :
</p>

[SASS font-face mixin](https://gist.github.com/jonathantneal/d0460e5c2d5d7f9bc5e6)

**Comment by mahdi-alavi** [comment]
<p dir="rtl">
سلام
با توجه به #104 سه تا پیشنهاد دارم
</p>
<p dir="rtl">
اول: همون‌طور که جناب @zoghal گفتند، در وزن‌های معمولی پسوند <kbd>regular</kbd> اضافه بشه
</p>
<p dir="rtl">
دوم: فونت‌های اصلی که کامل هستند در پوشه‌ای به نام <kbd>Complete-Font</kbd> قرار بگیرند
</p>
<p dir="rtl">
سوم: در اسامی فونت در هر چهار حالت (فونت کامل، اعداد فارسی، اعداد فارسی بدون لاتین و بدون لاتین) فقط از پسوند حجم فونت استفاده بشه،
یعنی دیگه نوع فونت در اسم فونت ذکر نشه
</p>
<p dir="rtl">
 در حال حاضر مثلا در پوشه اعداد فارسی نام‌گذاری به این‌صورت هست <kbd>Vazir-Light-FD</kbd> که به نظرم نیازی به ذکر نوع فونت نیست و بشه <kbd>Vazir-Light</kbd> مثل فونت‌های اصلی کافی هست و تفاوت فونت‌ها تنها بر اساس پوشه‌بندی مشخص بشه
</p>
<p dir="rtl">
نمونه کامل #107
</p>

**Comment by rastikerdar** [comment]
۱. همانطور که در آن ایشو نیز مطرح شد تغییر ساختار در حال حاضر به صلاح نیست با توجه به اینکه پروژه‌های متعددی بر مبنای وضعیت فعلی کار می‌کند. چه آنهایی که مستقیما دانلود می‌کنند و چه آنهایی که از ان.پی.ام نود استفاده می‌کنند. هرگونه تغییر، تمامی کاربران را به زحمت می‌اندازد.
۲. به دلیل نخست نمی‌توانیم
۳. اسامی فونت‌ها به این دلیل متفاوت می‌باشد که تمامی آنها در کنار هم قابل نصب می‌باشند. یعنی کاربران دسکتاپ می‌توانند همزمان تمامی حالات را بر سیستم فعال داشته باشند با اسامی متفاوت. در واقع امکان یکسان سازی نام‌ها تنها برای وب امکام پذیر است.
همچنین:
Explicit is better than implicit.

من فکر می‌کنم اینکه ما در هر پوشه‌ای فونت‌فیس.سی‌اس‌اس مخصوص به خودش قرار دهیم و همچنین در پوشه اصلی یک فایل  سَس مستقل برای دسترسی به کل ساختار ایده‌ بدی نباشه.

**Comment by mahdi-alavi** [comment]
در مورد اول و دوم: قبلا هم خدمت‌تون یه راه حل ساده گفتم
میشه پوشه‌بندی‌های جدید رو کنار پوشه‌بندی فعلی اضافه کرد
و لزومی نداره کلا پوشه‌بندی تغییر کنه
در کنار این‌کار یه پیام هم می‌شه گذاشت که در نسخه بعدی تنها سبک جدید اعمال میشه
در مورد سوم: واقعا خیلی بعید می‌دونم کسی توی ویندوز غیر از حالت کامل از نوع دیگه‌ای استفاده کنه، چون اصلا کاربرد نداره
در هر صورت این نظر من، تصمیم نهایی با شماست (:

**Comment by rastikerdar** [comment]
راستش من به این نتیجه رسیدم که این گونه موارد که تا حدودی هم سلیقه‌ای است در خود مخزن نیاید که نگهداریش هم سخت‌تر نشه. می‌تونه به عنوان روش‌های آموزشی در صفحات راهنمای وبسایت یا دیگر وبسایت‌های آموزشی ارائه بشه. همچنین ساختار پروژه کلا تغییر کرده.
از مشارکت همه دوستان ممنونم.
