### ISSUE TITLE
کامل نبودن گلیف‌های لاتین

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazirmatn#93]
فونت وزیر شامل حروف‌های پایه، ارقام و برخی علائم انگیلسی است که به جهت کاهش حجم سایر موارد از آن حذف شده.
در این [توییت](https://twitter.com/Prmasadi/status/985211223573753859) به ایراد اشاره شده
![screenshot from 2018-04-14 23-35-11](https://user-images.githubusercontent.com/3116038/38771692-c4647b90-403c-11e8-826c-ff7550fd9ae9.png)

بنا به توییت، فونت ایران‌سنس فاقد اون دو تا مربع است که احتمالا طی تلاش ناموفق برای خواندن از فونت سیستم‌عامل که بر روی وزیر تنظیم شده است به شکل مربع درآمده است.

می‌توان بخش لاتین را کامل کرد که پیامدش افزایش حجم فونت است.

**Comment by arminmon** [comment]
<div dir="rtl">
راه حل:
</br>
تعریف font-range داخل @font-face
</br>
بازه‌ی 0600 تا 06ff گلیف‌های حروف و ارقام عربی رو پوشش می‌ده.
خیلی راحت می‌شه از نسخه بدون حروف لاتین وزیر استفاده کرد و برای سایر گلیف‌ها از فونت بعدی تعریف شده داخل font-family به عنوان fallback استفاده کرد.
<br>
من به خاطر مشکلی که با ارتفاع حروف لاتین فونت وزیر داشتم مجبور شدم داخل وب‌سایت این کار رو انجام بدم تا فقط در صورت وجود حروف فارسی از وزیر استفاده بشه.
که البته bug این موضوع هم اینه که امکان داره با ورود اولین حرف فارسی در وب‌سایت، دوباره از ارتفاع فونت وزیر استفاده بشه
</div>
<code>
@font-face {
font-range: U+0600-06ff;
}
</code>

**Comment by rastikerdar** [comment]
ممنونم برای این نکته. البته فکر می‌کنم منظورتون این بوده:
`unicode-range: U+0600-06ff;`

**Comment by arminmon** [comment]
> ممنونم برای این نکته. البته فکر می‌کنم منظورتون این بوده:
> `unicode-range: U+0600-06ff;`

آخ آخ. اشتباه از من بوده.

**Comment by SMAH1** [comment]
من در برخی نرم‌افزار هایم هم از فونت وزیر استفاده می کنم.به نظرم باید به نوعی نسخه ای تکملی (شامل گلیف های فارسی و انگلیسی) باشد تا در اینگونه موارد مشکلی ایجاد نشود

**Comment by rastikerdar** [comment]
در نسخه وزیرمتن ۳۲ حروف لاتین کامل شد
https://github.com/rastikerdar/vazirmatn/releases
